// Auto-generated Hindi/Marathi translations for English+Gujarati UI strings.
// Keyed by the English source string; used by t4() in src/lib/t4.ts.
export const AUTO_TX: Record<string, { hi?: string; mr?: string }> = {
  "Your career roadmap": { hi: "आपका करियर रोडमैप", mr: "तुमचा करिअर रोडमॅप" },
  "Stage-by-stage path from Class 8 to senior roles.": { hi: "कक्षा 8 से लेकर सीनियर पदों तक चरण-दर-चरण मार्ग।", mr: "इयत्ता 8 वी पासून वरिष्ठ पदांपर्यंत टप्प्याटप्प्याने जाणारा मार्ग." },
  "Salary": { hi: "सैलरी", mr: "पगार" },
  "Online": { hi: "ऑनलाइन", mr: "ऑनलाइन" },
  "Offline mode": { hi: "ऑफलाइन मोड", mr: "ऑफलाइन मोड" },
  "Sync now": { hi: "अभी सिंक करें", mr: "आता सिंक करा" },
  "Inside the report": { hi: "रिपोर्ट के अंदर", mr: "रिपोर्टच्या आत" },
  "What's inside your 20-page PDF": { hi: "आपके 20-पेज के PDF में क्या है", mr: "तुमच्या 20-पानांच्या PDF मध्ये काय आहे" },
  "Every page is generated from your answers — no template reports.": { hi: "हर पेज आपके उत्तरों के आधार पर तैयार किया गया है — कोई रेडीमेड टेम्पलेट नहीं।", mr: "प्रत्येक पान तुमच्या उत्तरांवरून तयार केले आहे — कोणतेही तयार टेम्पलेट नाही." },
  "Personality summary": { hi: "व्यक्तित्व सारांश", mr: "व्यक्तिमत्त्व सारांश" },
  "AI-written in your language": { hi: "आपकी भाषा में AI द्वारा लिखित", mr: "तुमच्या भाषेत AI द्वारे लिखित" },
  "Holland code chart": { hi: "Holland code चार्ट", mr: "Holland code चार्ट" },
  "8 intelligences": { hi: "8 बुद्धिमत्ताएं", mr: "8 बुद्धिमत्ता" },
  "Aptitude scores": { hi: "एप्टीट्यूड स्कोर", mr: "अ‍ॅप्टिट्यूड स्कोअर" },
  "5 domains": { hi: "5 डोमेन", mr: "5 डोमेन्स" },
  "Top 5 streams": { hi: "टॉप 5 स्ट्रीम्स", mr: "टॉप 5 स्ट्रीम्स" },
  "with match %": { hi: "मैच % के साथ", mr: "मॅच % सह" },
  "12+ careers": { hi: "12+ करियर", mr: "12+ करिअर" },
  "with salary ranges": { hi: "सैलरी रेंज के साथ", mr: "पगार श्रेणीसह" },
  "90-day action plan": { hi: "90-दिनों का एक्शन प्लान", mr: "90-दिवसांचा अ‍ॅक्शन प्लॅन" },
  "weekly steps": { hi: "साप्ताहिक कदम", mr: "साप्ताहिक टप्पे" },
  "Note for parents": { hi: "माता-पिता के लिए नोट", mr: "पालकांसाठी टीप" },
  "bilingual": { hi: "द्विभाषी", mr: "द्विभाषिक" },
  "Change colors": { hi: "रंग बदलें", mr: "रंग बदला" },
  "Color theme": { hi: "कलर थीम", mr: "कलर थीम" },
  "Dark mode": { hi: "डार्क मोड", mr: "डार्क मोड" },
  "Light mode": { hi: "लाइट मोड", mr: "लाइट मोड" },
  "Take the test": { hi: "टेस्ट दें", mr: "टेस्ट द्या" },
  "60-second vibe check": { hi: "60-सेकंड वाइब चेक", mr: "60-सेकंदांचा वाइब चेक" },
  "What's your vibe?": { hi: "आपकी वाइब क्या है?", mr: "तुमची वाइब काय आहे?" },
  "5 quick questions. Instant vibe. Then dive into the deep 25-min test.": { hi: "5 झटपट सवाल। तुरंत वाइब। फिर 25-मिनट का विस्तृत टेस्ट दें।", mr: "5 सोपे प्रश्न. झटपट वाइब. त्यानंतर सविस्तर 25-मिनिटांची टेस्ट द्या." },
  "Start vibe check": { hi: "वाइब चेक शुरू करें", mr: "वाइब चेक सुरू करा" },
  "Skip to full test": { hi: "सीधे पूरी टेस्ट पर जाएं", mr: "थेट संपूर्ण टेस्टवर जा" },
  "Question": { hi: "प्रश्न", mr: "प्रश्न" },
  "of": { hi: "में से", mr: "पैकी" },
  "Your vibe is": { hi: "आपकी वाइब है", mr: "तुमची वाइब आहे" },
  "Matches:": { hi: "मैचेस:", mr: "मॅचेस:" },
  "Take the full 25-min test → Free report": { hi: "पूरी 25-मिनट की टेस्ट दें → फ्री रिपोर्ट", mr: "संपूर्ण 25-मिनिटांची टेस्ट द्या → मोफत रिपोर्ट" },
  "Retake": { hi: "फिर से दें", mr: "पुन्हा द्या" },
  "Free, always": { hi: "हमेशा फ्री", mr: "नेहमी मोफत" },
  "No paywalls. No login walls. Equal access for every student in Gujarat.": { hi: "कोई फीस नहीं। कोई लॉगिन की बाध्यता नहीं। गुजरात के हर छात्र के लिए समान अवसर।", mr: "कोणतेही शुल्क नाही. कोणतीही लॉगिनची सक्ती नाही. गुजरातमधील प्रत्येक विद्यार्थ्याला समान संधी." },
  "Bilingual-first": { hi: "द्विभाषी प्राथमिकता", mr: "द्विभाषिक प्राधान्य" },
  "Gujarati and English at equal quality — not translations, original content.": { hi: "गुजराती और अंग्रेजी समान गुणवत्ता में — अनुवाद नहीं, मूल सामग्री।", mr: "गुजराती आणि इंग्रजी समान दर्जात — भाषांतर नाही, मूळ मजकूर." },
  "Data dignity": { hi: "डेटा की गरिमा और सुरक्षा", mr: "डेटाची गोपनीयता आणि प्रतिष्ठा" },
  "We never sell student data. Ever. Your responses generate your report — nothing more.": { hi: "हम छात्रों का डेटा कभी नहीं बेचते। कभी नहीं। आपके जवाबों से केवल आपकी रिपोर्ट बनती है — और कुछ नहीं।", mr: "आम्ही विद्यार्थ्यांचा डेटा कधीही विकत नाही. कधीच नाही. तुमच्या उत्तरांवरून केवळ तुमचा रिपोर्ट तयार होतो — बाकी काही नाही." },
  "Built by educators": { hi: "शिक्षकों द्वारा निर्मित", mr: "शिक्षकांनी तयार केलेले" },
  "Not edtech — a 100-year-old school that actually knows students.": { hi: "कोई एडटेक कंपनी नहीं — 100 साल पुराना स्कूल जो वास्तव में छात्रों को समझता है।", mr: "कोणतीही एडटेक कंपनी नाही — 100 वर्षे जुनी शाळा, जी विद्यार्थ्यांना खरोखर ओळखते." },
  "Our story": { hi: "हमारी कहानी", mr: "आमची गोष्ट" },
  "Every student deserves to choose with clarity.": { hi: "हर छात्र को स्पष्टता के साथ करियर चुनने का हक है।", mr: "प्रत्येक विद्यार्थ्याला स्पष्टतेने करिअर निवडण्याचा अधिकार आहे." },
  "HBK Careers is built by The H B Kapadia New High School, Ahmedabad — a school that has been teaching Gujarat's students since 1925. We noticed that most decisions after Class 10 are made out of fear, family pressure, or incomplete information. So we built this — free, bilingual, and grounded in real psychometric science.": { hi: "HBK Careers को The H B Kapadia New High School, Ahmedabad द्वारा बनाया गया है — एक ऐसा स्कूल जो 1925 से गुजरात के छात्रों को शिक्षित कर रहा है। हमने देखा कि Class 10 के बाद ज्यादातर फैसले डर, पारिवारिक दबाव या अधूरी जानकारी के कारण लिए जाते हैं। इसलिए हमने इसे बनाया — पूरी तरह फ्री, द्विभाषी और वास्तविक साइकोमेट्रिक विज्ञान पर आधारित।", mr: "HBK Careers ची निर्मिती The H B Kapadia New High School, Ahmedabad द्वारे करण्यात आली आहे — ही शाळा 1925 पासून गुजरातमधील विद्यार्थ्यांना घडवत आहे. आमच्या असे लक्षात आले की Class 10 नंतरचे बहुतांश निर्णय भीती, कौटुंबिक दबाव किंवा अपुऱ्या माहितीमुळे घेतले जातात. म्हणूनच आम्ही हे व्यासपीठ तयार केले — पूर्णपणे मोफत, द्विभाषिक आणि खऱ्या सायकोमेट्रिक विज्ञानावर आधारित." },
  "What we stand for": { hi: "हमारा उद्देश्य", mr: "आमचे ध्येय" },
  "Find your direction — free": { hi: "अपनी सही दिशा खोजें — मुफ़्त", mr: "आपली योग्य दिशा शोधा — मोफत" },
  "For schools": { hi: "स्कूलों के लिए", mr: "शाळांसाठी" },
  "Career Library": { hi: "करियर लाइब्रेरी", mr: "करिअर लायब्ररी" },
  "Every career, A to Z — in one place": { hi: "हर करियर, A to Z — एक ही जगह पर", mr: "प्रत्येक करिअर, A to Z — एकाच ठिकाणी" },
  "Search 48 streams and 1,600+ professions — each with the study path, entrance exams, top institutes, salary bands and growth ladder.": { hi: "48 स्ट्रीम्स और 1,600+ प्रोफेशन्स खोजें — हर एक के लिए पढ़ाई का रास्ता, entrance exams, टॉप संस्थान, सैलरी बैंड और करियर ग्रोथ की जानकारी।", mr: "48 स्ट्रीम्स आणि 1,600+ प्रोफेशन्स शोधा — प्रत्येकासाठी अभ्यासाचा मार्ग, entrance exams, टॉप संस्था, सॅलरी बँड्स आणि करिअर वाढीची माहिती." },
  "streams": { hi: "स्ट्रीम्स", mr: "स्ट्रीम्स" },
  "professions": { hi: "प्रोफेशन्स", mr: "प्रोफेशन्स" },
  "entrance exams": { hi: "प्रवेश परीक्षाएं", mr: "प्रवेश परीक्षा" },
  "top institutes": { hi: "टॉप संस्थान", mr: "सर्वोत्कृष्ट संस्था" },
  "Search any career — e.g. pilot, data science, chef, ethical hacking…": { hi: "कोई भी करियर खोजें — जैसे pilot, data science, chef, ethical hacking…", mr: "कोणतेही करिअर शोधा — उदा. pilot, data science, chef, ethical hacking…" },
  "All": { hi: "सभी", mr: "सर्व" },
  "Matching professions": { hi: "मिलते-जुलते प्रोफेशन्स", mr: "संबंधित प्रोफेशन्स" },
  "Career streams": { hi: "करियर स्ट्रीम्स", mr: "करिअर स्ट्रीम्स" },
  "No streams matched your search.": { hi: "आपकी खोज से कोई स्ट्रीम नहीं मिली।", mr: "तुमच्या शोधाशी कोणतीही स्ट्रीम जुळली नाही." },
  "exams": { hi: "परीक्षाएं", mr: "परीक्षा" },
  "institutes": { hi: "संस्थान", mr: "संस्था" },
  "Open professions": { hi: "प्रोफेशन्स देखें", mr: "प्रोफेशन्स पहा" },
  "en": { hi: "en", mr: "en" },
  "Gujarat-focused": { hi: "गुजरात-केंद्रित", mr: "गुजरात-केंद्रित" },
  "Duration": { hi: "अवधि", mr: "कालावधी" },
  "Eligibility": { hi: "पात्रता", mr: "पात्रता" },
  "Entrance exams": { hi: "प्रवेश परीक्षाएं", mr: "प्रवेश परीक्षा" },
  "Avg salary": { hi: "औसत सैलरी", mr: "सरासरी सॅलरी" },
  "What you'll study": { hi: "आप क्या पढ़ेंगे", mr: "तुम्ही काय शिकाल" },
  "What a typical day looks like": { hi: "एक सामान्य दिन कैसा होता है", mr: "एक सामान्य दिवस कसा असतो" },
  "Top colleges in Gujarat": { hi: "गुजरात के टॉप कॉलेज", mr: "गुजरातमधील टॉप कॉलेजेस" },
  "Career roles": { hi: "करियर रोल्स", mr: "करिअरमधील विविध भूमिका" },
  "Career growth path": { hi: "करियर ग्रोथ पाथ", mr: "करिअरच्या प्रगतीचा मार्ग" },
  "Why study this in Gujarat?": { hi: "यह गुजरात में क्यों पढ़ें?", mr: "हे गुजरातमध्ये का शिकावे?" },
  "Scholarships & financial aid": { hi: "स्कॉलरशिप और आर्थिक सहायता", mr: "स्कॉलरशिप्स आणि आर्थिक सहाय्य" },
  "Entrance exam quick links": { hi: "प्रवेश परीक्षा क्विक लिंक्स", mr: "प्रवेश परीक्षा क्विक लिंक्स" },
  "When": { hi: "कब", mr: "केव्हा" },
  "Frequently asked questions": { hi: "अक्सर पूछे जाने वाले सवाल", mr: "नेहमी विचारले जाणारे प्रश्न" },
  "Other paths in this stream": { hi: "इस स्ट्रीम में अन्य रास्ते", mr: "या शाखेतील इतर मार्ग" },
  "Is this path right for you?": { hi: "क्या यह रास्ता आपके लिए सही है?", mr: "हा मार्ग तुमच्यासाठी योग्य आहे का?" },
  "Take the free psychometric test and get a 20-page personalised report.": { hi: "फ्री साइकोमेट्रिक टेस्ट दें और 20-पेज की पर्सनलाइज्ड रिपोर्ट पाएं।", mr: "मोफत सायकोमेट्रिक टेस्ट द्या आणि 20-पानांचा वैयक्तिक अहवाल मिळवा." },
  "All streams": { hi: "सभी स्ट्रीम्स", mr: "सर्व शाखा (Streams)" },
  "Gujarat highlights": { hi: "गुजरात की मुख्य बातें", mr: "गुजरातच्या ठळक बाबी" },
  "Career Paths": { hi: "करियर पाथ्स", mr: "करिअर मार्ग" },
  "Salary range": { hi: "सैलरी रेंज", mr: "वेतन श्रेणी (सॅलरी रेंज)" },
  "Top colleges (Gujarat)": { hi: "टॉप कॉलेज (गुजरात)", mr: "टॉप कॉलेजेस (गुजरात)" },
  "Read more": { hi: "और पढ़ें", mr: "अधिक वाचा" },
  "Want India-wide reference?": { hi: "पूरे भारत के संदर्भ में देखना चाहते हैं?", mr: "अखिल भारतीय संदर्भात माहिती हवी आहे का?" },
  "Browse the Career Handbook for 935+ professions and 1,400+ top Indian institutes across 20 streams.": { hi: "20 स्ट्रीम्स में 935+ प्रोफेशन्स और 1,400+ टॉप भारतीय संस्थानों के लिए करियर हैंडबुक देखें।", mr: "20 शाखांमधील 935+ व्यवसाय आणि 1,400+ आघाडीच्या भारतीय संस्थांसाठी करिअर हँडबुक पहा." },
  "Open Handbook": { hi: "हैंडबुक खोलें", mr: "हँडबुक उघडा" },
  "Still unsure?": { hi: "अब भी तय नहीं कर पा रहे?", mr: "अजूनही संभ्रमात आहात?" },
  "100% Gujarat-focused": { hi: "100% गुजरात-केंद्रित", mr: "100% गुजरात-केंद्रित" },
  "Career Guidance — Gujarat": { hi: "करियर गाइडेंस — गुजरात", mr: "करिअर मार्गदर्शन — गुजरात" },
  "Top Gujarat colleges for every stream after Class 12 — careers, courses, entrance exams (GUJCET, JEE, NEET, CLAT, NID), ACPC counselling, MYSY scholarship and state schemes — all in one place.": { hi: "12वीं के बाद हर स्ट्रीम के लिए गुजरात के टॉप कॉलेज — करियर, कोर्सेस, प्रवेश परीक्षाएं (GUJCET, JEE, NEET, CLAT, NID), ACPC काउंसलिंग, MYSY स्कॉलरशिप और राज्य की योजनाएं — सब एक ही जगह।", mr: "इयत्ता 12वीनंतर प्रत्येक शाखेसाठी गुजरातमधील टॉप कॉलेजेस — करिअर, कोर्सेस, प्रवेश परीक्षा (GUJCET, JEE, NEET, CLAT, NID), ACPC समुपदेशन, MYSY स्कॉलरशिप आणि राज्य सरकारच्या योजना — सर्व काही एकाच ठिकाणी." },
  "Streams": { hi: "स्ट्रीम्स", mr: "स्ट्रीम्स" },
  "Career paths": { hi: "करियर पथ", mr: "करिअर मार्ग" },
  "Gujarat colleges": { hi: "गुजरात के कॉलेज", mr: "गुजरातमधील कॉलेजेस" },
  "MBBS seats": { hi: "MBBS सीटें", mr: "MBBS जागा" },
  "ITI centres": { hi: "ITI केंद्र", mr: "ITI केंद्रे" },
  "Gujarat's Top Colleges — Complete Directory": { hi: "गुजरात के टॉप कॉलेज — पूरी डायरेक्टरी", mr: "गुजरातमधील टॉप कॉलेजेस — संपूर्ण डिरेक्टरी" },
  "Looking for a specific college? Open Find Your College (Gujarat + India)": { hi: "कोई विशिष्ट कॉलेज ढूंढ रहे हैं? Find Your College (Gujarat + India) खोलें", mr: "एखादे विशिष्ट कॉलेज शोधत आहात? Find Your College (Gujarat + India) उघडा" },
  "Showing": { hi: "दिखाया जा रहा है", mr: "दाखवत आहे" },
  "No results found.": { hi: "कोई परिणाम नहीं मिला।", mr: "कोणतेही निकाल आढळले नाहीत." },
  "Major Entrance Exams": { hi: "प्रमुख प्रवेश परीक्षाएं", mr: "प्रमुख प्रवेश परीक्षा" },
  "Gujarat and national-level exams — with dates and official websites.": { hi: "गुजरात और राष्ट्रीय स्तर की परीक्षाएं — तारीखों और आधिकारिक वेबसाइटों के साथ।", mr: "गुजरात आणि राष्ट्रीय स्तरावरील परीक्षा — तारखा आणि अधिकृत वेबसाइट्ससह." },
  "Gujarat — Scholarships & Counselling": { hi: "गुजरात — स्कॉलरशिप और काउंसलिंग", mr: "गुजरात — स्कॉलरशिप आणि काउन्सिलिंग" },
  "MYSY Scholarship": { hi: "MYSY Scholarship", mr: "MYSY Scholarship" },
  "Mukhyamantri Yuva Swavalamban Yojana — up to ₹2L/year for tuition + hostel + books.": { hi: "Mukhyamantri Yuva Swavalamban Yojana — ट्यूशन + हॉस्टल + किताबों के लिए ₹2L/वर्ष तक।", mr: "Mukhyamantri Yuva Swavalamban Yojana — ट्यूशन + हॉस्टेल + पुस्तकांसाठी ₹2L/वर्ष पर्यंत." },
  "Post-GUJCET state college admission counselling.": { hi: "GUJCET के बाद राज्य कॉलेज प्रवेश काउंसलिंग।", mr: "GUJCET नंतर राज्य कॉलेज प्रवेश काउन्सिलिंग." },
  "ACPC Medical": { hi: "ACPC Medical", mr: "ACPC Medical" },
  "NEET-based state counselling for MBBS, BDS, AYUSH, B.V.Sc, BPT.": { hi: "MBBS, BDS, AYUSH, B.V.Sc, BPT के लिए NEET-आधारित राज्य काउंसलिंग।", mr: "MBBS, BDS, AYUSH, B.V.Sc, BPT साठी NEET-आधारित राज्य काउन्सिलिंग." },
  "3-yr Diploma Engineering admission after Class 10.": { hi: "कक्षा 10वीं के बाद 3-वर्षीय Diploma Engineering में प्रवेश।", mr: "इयत्ता 10वीनंतर 3-वर्षीय Diploma Engineering प्रवेश." },
  "Digital Gujarat Scholarships": { hi: "Digital Gujarat Scholarships", mr: "Digital Gujarat Scholarships" },
  "Post-matric scholarships for SC/ST/OBC/EBC/Minority students.": { hi: "SC/ST/OBC/EBC/Minority छात्रों के लिए पोस्ट-मैट्रिक स्कॉलरशिप।", mr: "SC/ST/OBC/EBC/Minority विद्यार्थ्यांसाठी पोस्ट-मॅट्रिक स्कॉलरशिप." },
  "Kaushalya — Skill University": { hi: "Kaushalya — Skill University", mr: "Kaushalya — Skill University" },
  "India's first state skill university; ITI, Diploma & degree pathways.": { hi: "भारत की पहली राज्य कौशल यूनिवर्सिटी; ITI, Diploma और डिग्री मार्ग।", mr: "भारतातील पहिले राज्य कौशल्य विद्यापीठ; ITI, Diploma आणि पदवी मार्ग." },
  "Still unsure which stream to pick?": { hi: "अभी भी तय नहीं कर पा रहे कि कौन सी स्ट्रीम चुनें?", mr: "कोणती स्ट्रीम निवडायची याबद्दल अजूनही साशंक आहात?" },
  "Take the free psychometric test and get a 20-page personalised report — Gujarat-focused recommendations based on your RIASEC, aptitude and multiple-intelligences profile.": { hi: "निःशुल्क साइकोमेट्रिक टेस्ट लें और 20-पेज की पर्सनलाइज्ड रिपोर्ट पाएं — आपके RIASEC, एप्टीट्यूड और मल्टीपल-इंटेलिजेंस प्रोफाइल पर आधारित गुजरात-केंद्रित सिफारिशें।", mr: "मोफत सायकोमेट्रिक टेस्ट द्या आणि मिळवा 20-पानांचा वैयक्तिक अहवाल — तुमच्या RIASEC, अ‍ॅपटीट्यूड आणि मल्टिपल-इंटेलिजन्स प्रोफाइलवर आधारित गुजरात-केंद्रित शिफारसी." },
  "Counselling": { hi: "काउंसलिंग", mr: "काउन्सिलिंग" },
  "Courses": { hi: "कोर्सेस", mr: "कोर्सेस" },
  "Related streams": { hi: "संबंधित स्ट्रीम्स", mr: "संबंधित स्ट्रीम्स" },
  "Gujarat Colleges Directory": { hi: "गुजरात कॉलेज डायरेक्टरी", mr: "गुजरात कॉलेज डिरेक्टरी" },
  "Search by stream, district and type. Includes fees, hostel, scholarships and entrance exams.": { hi: "स्ट्रीम, ज़िला और प्रकार के अनुसार खोजें। इसमें फीस, हॉस्टल, स्कॉलरशिप और प्रवेश परीक्षाएं शामिल हैं।", mr: "स्ट्रीम, जिल्हा आणि प्रकारानुसार शोधा. यामध्ये फी, हॉस्टेल, शिष्यवृत्ती आणि प्रवेश परीक्षा समाविष्ट आहेत." },
  "Search college or city…": { hi: "कॉलेज या शहर खोजें…", mr: "कॉलेज किंवा शहर शोधा…" },
  "All districts": { hi: "सभी ज़िले", mr: "सर्व जिल्हे" },
  "Type": { hi: "प्रकार", mr: "प्रकार" },
  "Loading…": { hi: "लोड हो रहा है…", mr: "लोड होत आहे…" },
  "colleges": { hi: "कॉलेजेस", mr: "कॉलेजेस" },
  "No colleges yet. An admin can seed the directory or import an Excel sheet.": { hi: "अभी कोई कॉलेज नहीं है। एडमिन डायरेक्टरी जोड़ सकते हैं या Excel शीट इंपोर्ट कर सकते हैं।", mr: "अद्याप कोणतेही कॉलेज नाही. ॲडमिन डिरेक्टरी तयार करू शकतात किंवा Excel शीट इंपोर्ट करू शकतात." },
  "Open admin page": { hi: "एडमिन पेज खोलें", mr: "ॲडमिन पेज उघडा" },
  "Entrance Exams": { hi: "प्रवेश परीक्षाएं", mr: "प्रवेश परीक्षा" },
  "e.g. JEE, NEET, CUET, design...": { hi: "उदा. JEE, NEET, CUET, design...", mr: "उदा. JEE, NEET, CUET, design..." },
  "All fields": { hi: "सभी क्षेत्र", mr: "सर्व क्षेत्रे" },
  "All levels": { hi: "सभी स्तर", mr: "सर्व स्तर" },
  "All scope": { hi: "सभी स्कोप", mr: "सर्व स्कोप" },
  "filter(s)": { hi: "फ़िल्टर", mr: "फिल्टर" },
  "Clear all": { hi: "सभी हटाएं", mr: "सर्व काढा" },
  "No exams match": { hi: "कोई परीक्षा नहीं मिली", mr: "कोणतीही परीक्षा आढळली नाही" },
  "By": { hi: "द्वारा", mr: "द्वारे" },
  "Eligibility:": { hi: "पात्रता:", mr: "पात्रता:" },
  "Pattern:": { hi: "पैटर्न:", mr: "पॅटर्न:" },
  "Not sure which exam fits you?": { hi: "समझ नहीं आ रहा कौन सी परीक्षा आपके लिए सही है?", mr: "तुमच्यासाठी कोणती परीक्षा योग्य आहे हे समजत नाहीये?" },
  "Take the free aptitude test for personalised recommendations.": { hi: "व्यक्तिगत सुझावों के लिए मुफ़्त एप्टीट्यूड टेस्ट दें।", mr: "वैयक्तिक शिफारशींसाठी मोफत ॲप्टिट्यूड टेस्ट द्या." },
  "From students, parents and schools across Gujarat.": { hi: "गुजरात भर के छात्रों, अभिभावकों और स्कूलों की ओर से।", mr: "संपूर्ण गुजरातमधील विद्यार्थी, पालक आणि शाळांकडून." },
  "Full College Directory": { hi: "कॉलेजों की पूरी डायरेक्टरी", mr: "कॉलेजांची संपूर्ण डिरेक्टरी" },
  "Find Your College": { hi: "अपना कॉलेज खोजें", mr: "तुमचे कॉलेज शोधा" },
  "e.g. IIT, MBBS, Ahmedabad, Engineering, NID...": { hi: "उदा. IIT, MBBS, Ahmedabad, Engineering, NID...", mr: "उदा. IIT, MBBS, Ahmedabad, Engineering, NID..." },
  "All regions": { hi: "सभी क्षेत्र", mr: "सर्व प्रदेश" },
  "Rest of India": { hi: "शेष भारत", mr: "उर्वरित भारत" },
  "All states": { hi: "सभी राज्य", mr: "सर्व राज्ये" },
  "All cities": { hi: "सभी शहर", mr: "सर्व शहरे" },
  "All categories": { hi: "सभी श्रेणियां", mr: "सर्व श्रेणी" },
  "All types": { hi: "सभी प्रकार", mr: "सर्व प्रकार" },
  "Results": { hi: "परिणाम", mr: "निकाल" },
  "active filter(s)": { hi: "सक्रिय फ़िल्टर", mr: "सक्रिय फिल्टर्स" },
  "Clear all filters": { hi: "सभी फ़िल्टर हटाएं", mr: "सर्व फिल्टर्स काढा" },
  "No colleges match your search": { hi: "आपकी खोज से मेल खाता कोई कॉलेज नहीं मिला", mr: "तुमच्या शोधाशी जुळणारे कोणतेही कॉलेज आढळले नाही" },
  "Try changing or clearing the filters.": { hi: "फ़िल्टर बदलने या हटाने का प्रयास करें।", mr: "फिल्टर्स बदलून किंवा काढून पुन्हा प्रयत्न करा." },
  "Clear filters": { hi: "फ़िल्टर हटाएं", mr: "फिल्टर्स काढा" },
  "Not sure which stream is right for you?": { hi: "तय नहीं कर पा रहे कि आपके लिए कौन सी स्ट्रीम सही है?", mr: "तुमच्यासाठी कोणती स्ट्रीम योग्य आहे याबद्दल खात्री नाही?" },
  "Take the free aptitude test — RIASEC + interest-based recommendations.": { hi: "मुफ़्त एप्टीट्यूड टेस्ट लें — RIASEC + रुचि-आधारित सुझाव।", mr: "मोफत ॲप्टिट्यूड टेस्ट घ्या — RIASEC + आवडीनुसार शिफारसी." },
  "Print": { hi: "प्रिंट करें", mr: "प्रिंट करा" },
  "Print / Save": { hi: "प्रिंट / सेव करें", mr: "प्रिंट / सेव्ह करा" },
  "Search in this section…": { hi: "इस सेक्शन में खोजें…", mr: "या विभागात शोधा…" },
  "Institute": { hi: "संस्थान", mr: "संस्था" },
  "Entrance": { hi: "प्रवेश परीक्षा", mr: "प्रवेश परीक्षा" },
  "Career Guidance — India": { hi: "करियर मार्गदर्शन — India", mr: "करिअर मार्गदर्शन — India" },
  "Professions, Entrance Exams & Top Institutes across 48 Streams": { hi: "48 स्ट्रीम में प्रोफेशन्स, प्रवेश परीक्षाएं और शीर्ष संस्थान", mr: "48 स्ट्रीम्समधील व्यवसाय, प्रवेश परीक्षा आणि अव्वल संस्था" },
  "Detailed reference list of career paths, major entrance exams and India's top-ranked institutes for every stream.": { hi: "हर स्ट्रीम के लिए करियर विकल्पों, प्रमुख प्रवेश परीक्षाओं और भारत के शीर्ष रैंक वाले संस्थानों की विस्तृत संदर्भ सूची।", mr: "प्रत्येक स्ट्रीमसाठी करिअर मार्ग, प्रमुख प्रवेश परीक्षा आणि भारतातील अव्वल दर्जाच्या संस्थांची सविस्तर संदर्भ सूची." },
  "© HBK Careers. Compiled in-house from public sources — official regulators and exam bodies including AICTE, NMC, BCI, ICAI, COA, NID, NIFT, NCHMCT, NTA, ACPC Gujarat and the relevant ministries. Detailed sources are listed at the bottom of every stream page.": { hi: "© HBK Careers. सार्वजनिक स्रोतों से आंतरिक रूप से संकलित — आधिकारिक नियामकों और परीक्षा निकायों सहित AICTE, NMC, BCI, ICAI, COA, NID, NIFT, NCHMCT, NTA, ACPC Gujarat और संबंधित मंत्रालय। विस्तृत स्रोत प्रत्येक स्ट्रीम पेज के नीचे सूचीबद्ध हैं।", mr: "© HBK Careers. सार्वजनिक स्रोतांवरून अंतर्गत संकलित — AICTE, NMC, BCI, ICAI, COA, NID, NIFT, NCHMCT, NTA, ACPC Gujarat आणि संबंधित मंत्रालयांसह अधिकृत नियामक आणि परीक्षा मंडळे. तपशीलवार स्रोत प्रत्येक स्ट्रीम पेजच्या तळाशी सूचीबद्ध आहेत." },
  "Search streams…": { hi: "स्ट्रीम खोजें…", mr: "स्ट्रीम शोधा…" },
  "View details": { hi: "विवरण देखें", mr: "तपशील पहा" },
  "Science-backed": { hi: "वैज्ञानिक दृष्टिकोण पर आधारित", mr: "वैज्ञानिक पद्धतींवर आधारित" },
  "Uses RIASEC (Holland), Multiple Intelligences (Gardner) and a 5-domain aptitude battery — the same frameworks private counsellors charge ₹3,000–5,000 for.": { hi: "RIASEC (Holland), Multiple Intelligences (Gardner) और 5-domain aptitude battery का उपयोग करता है — वही फ्रेमवर्क जिसके लिए प्राइवेट काउंसलर ₹3,000–5,000 लेते हैं।", mr: "RIASEC (Holland), Multiple Intelligences (Gardner) आणि 5-domain aptitude battery चा वापर करते — तीच पद्धत ज्यासाठी खाजगी समुपदेशक ₹3,000–5,000 आकारतात." },
  "Real salary data": { hi: "वास्तविक सैलरी डेटा", mr: "प्रत्यक्ष पगाराचा डेटा" },
  "Every career shows entry, mid and senior salary ranges — for Gujarat and India.": { hi: "प्रत्येक करियर में एंट्री, मिड और सीनियर स्तर की सैलरी रेंज दिखाई जाती है — Gujarat और India के लिए।", mr: "प्रत्येक करिअरमध्ये एंट्री, मिड आणि सिनियर स्तरावरील पगाराची श्रेणी दर्शविली जाते — Gujarat आणि India साठी." },
  "Not just a report — a week-by-week plan you can work through with your child.": { hi: "केवल एक रिपोर्ट नहीं — सप्ताह-दर-सप्ताह योजना जिस पर आप अपने बच्चे के साथ मिलकर काम कर सकते हैं।", mr: "केवळ एक रिपोर्ट नाही — आठवडानिहाय योजना ज्यावर तुम्ही तुमच्या पाल्यासोबत मिळून काम करू शकता." },
  "Bilingual report": { hi: "द्विभाषी रिपोर्ट", mr: "द्विभाषिक रिपोर्ट" },
  "Full Gujarati and English versions. Read it in the language you're most comfortable with.": { hi: "पूर्ण Gujarati और English संस्करण। इसे उस भाषा में पढ़ें जिसमें आप सबसे सहज हों।", mr: "पूर्ण Gujarati आणि English आवृत्त्या. तुम्हाला ज्या भाषेत सर्वात सोपे वाटते त्या भाषेत वाचा." },
  "For parents": { hi: "माता-पिता के लिए", mr: "पालकांसाठी" },
  "Decide together. Without pressure.": { hi: "मिलकर निर्णय लें। बिना किसी दबाव के।", mr: "एकत्र निर्णय घ्या. कोणत्याही दबावाशिवाय." },
  "Let your child take the test. Then read the 20-page report together — in Gujarati or English. It's free, private, and built by a school you can trust.": { hi: "अपने बच्चे को यह टेस्ट देने दें। फिर मिलकर 20-पेज की रिपोर्ट पढ़ें — Gujarati या English में। यह निःशुल्क है, निजी है और आपके भरोसेमंद स्कूल द्वारा तैयार की गई है।", mr: "तुमच्या पाल्याला ही टेस्ट देऊ द्या. नंतर 20 पानांचा रिपोर्ट एकत्र वाचा — Gujarati किंवा English मध्ये. हे विनामूल्य, खाजगी आणि तुमच्या विश्वासातील शाळेने तयार केलेले आहे." },
  "Ask your child to take the test": { hi: "अपने बच्चे को टेस्ट देने के लिए कहें", mr: "तुमच्या पाल्याला टेस्ट देण्यास सांगा" },
  "Why parents trust HBK Careers": { hi: "माता-पिता HBK Careers पर भरोसा क्यों करते हैं", mr: "पालक HBK Careers वर विश्वास का ठेवतात" },
  "How to read the report together": { hi: "रिपोर्ट को साथ मिलकर कैसे पढ़ें", mr: "रिपोर्ट एकत्र कसा वाचावा" },
  "Start with the Personality Summary. Ask your child if it feels accurate.": { hi: "Personality Summary से शुरुआत करें। अपने बच्चे से पूछें कि क्या यह सही लगता है।", mr: "Personality Summary ने सुरुवात करा. तुमच्या पाल्याला विचारा की हे अचूक वाटते का." },
  "Look at the top 5 streams. Notice the match percentages.": { hi: "शीर्ष 5 स्ट्रीम्स देखें। मैच प्रतिशत पर ध्यान दें।", mr: "पहिले 5 स्ट्रीम्स पहा. मॅच टक्केवारीकडे लक्ष द्या." },
  "Review the salary ranges — these are real Gujarat figures.": { hi: "सैलरी रेंज देखें — ये Gujarat के वास्तविक आंकड़े हैं।", mr: "पगाराची श्रेणी तपासा — हे Gujarat मधील प्रत्यक्ष आकडे आहेत." },
  "Open the 90-day plan together. Take one step per week.": { hi: "90 दिनों की योजना को साथ मिलकर खोलें। प्रति सप्ताह एक कदम उठाएं।", mr: "90 दिवसांची योजना एकत्र उघडा. दर आठवड्याला एक पाऊल उचला." },
  "Saved to this device": { hi: "इस डिवाइस पर सहेजा गया", mr: "या डिव्हाइसवर सेव्ह केले" },
  "Please enter your full name": { hi: "कृपया अपना पूरा नाम दर्ज करें", mr: "कृपया तुमचे पूर्ण नाव प्रविष्ट करा" },
  "PDF downloaded": { hi: "PDF डाउनलोड हो गई", mr: "PDF डाउनलोड झाली" },
  "Scholarships Directory": { hi: "छात्रवृत्ति निर्देशिका", mr: "शिष्यवृत्ती निर्देशिका" },
  "Scholarships": { hi: "छात्रवृत्तियां", mr: "शिष्यवृत्ती" },
  "e.g. MYSY, NMMS, girls, merit...": { hi: "उदा. MYSY, NMMS, लड़कियाँ, मेरिट...", mr: "उदा. MYSY, NMMS, मुली, मेरिट..." },
  "scholarships": { hi: "छात्रवृत्तियां", mr: "शिष्यवृत्ती" },
  "No scholarships match": { hi: "कोई छात्रवृत्ति मेल नहीं खाती", mr: "कोणतीही शिष्यवृत्ती जुळत नाही" },
  "Looking for entrance exams?": { hi: "प्रवेश परीक्षाओं की तलाश है?", mr: "प्रवेश परीक्षा शोधत आहात?" },
  "JEE, NEET, GUJCET, CUET — full directory.": { hi: "JEE, NEET, GUJCET, CUET — पूरी डायरेक्टरी।", mr: "JEE, NEET, GUJCET, CUET — संपूर्ण डिरेक्टरी." },
  "Browse exams": { hi: "परीक्षाएं देखें", mr: "परीक्षा ब्राउझ करा" },
  "Where they are now": { hi: "आज वे कहाँ हैं", mr: "आज ते कुठे आहेत" },
  "Real students. Real paths.": { hi: "असली छात्र। असली राहें।", mr: "खरे विद्यार्थी. खरी वाटचाल." },
  "Gujarat students who used HBK Careers to find their direction — and made it happen.": { hi: "गुजरात के छात्र जिन्होंने अपनी सही दिशा खोजने के लिए HBK Careers का उपयोग किया — और उसे हासिल किया।", mr: "गुजरातमधील विद्यार्थी ज्यांनी योग्य दिशा शोधण्यासाठी HBK Careers चा वापर केला — आणि ते साध्य करून दाखवले." },
  "Your story is next.": { hi: "अगली कहानी आपकी है।", mr: "पुढची यशोगाथा तुमची आहे." },
  "Take the free test": { hi: "मुफ्त टेस्ट दें", mr: "मोफत टेस्ट द्या" },
  "Parent Sessions": { hi: "अभिभावक सत्र", mr: "पालक सत्र" },
  "College & exam guidance year-round": { hi: "साल भर कॉलेज और परीक्षा मार्गदर्शन", mr: "वर्षभर कॉलेज आणि परीक्षा मार्गदर्शन" },
  "Entrance Exam": { hi: "प्रवेश परीक्षा", mr: "प्रवेश परीक्षा" },
  "Thank you — request received!": { hi: "धन्यवाद — अनुरोध प्राप्त हुआ!", mr: "धन्यवाद — विनंती प्राप्त झाली!" },
  "Internship → first job. Build portfolio and certifications.": { hi: "इंटर्नशिप → पहली नौकरी। पोर्टफोलियो और सर्टिफिकेशन बनाएं।", mr: "इंटर्नशिप → पहिली नोकरी. पोर्टफोलिओ आणि सर्टिफिकेशन्स तयार करा." },
  "Everything in Standard": { hi: "Standard में सब कुछ", mr: "Standard मधील सर्वकाही" },
  "Everything in Essentials": { hi: "Essentials में सब कुछ", mr: "Essentials मधील सर्वकाही" },
  "Contact person *": { hi: "संपर्क व्यक्ति *", mr: "संपर्क व्यक्ती *" },
  "Standardised RIASEC, MI and aptitude tests. Class 6–12, in English & Gujarati.": { hi: "मानकीकृत RIASEC, MI और एप्टीट्यूड टेस्ट। Class 6–12, अंग्रेज़ी और गुजराती में।", mr: "प्रमाणित RIASEC, MI आणि ॲप्टिट्यूड टेस्ट. Class 6–12, इंग्रजी आणि गुजरातीमध्ये." },
  "Class 11–12": { hi: "कक्षा 11–12", mr: "इयत्ता 11–12" },
  "Specialise, lead small teams, optionally pursue PG/MBA.": { hi: "विशेषज्ञता हासिल करें, छोटी टीमों का नेतृत्व करें, वैकल्पिक रूप से PG/MBA करें।", mr: "विशेष प्रावीण्य मिळवा, छोट्या टीम्सचे नेतृत्व करा, हवे असल्यास PG/MBA करा." },
  "Role (Principal, Coordinator...)": { hi: "पद (Principal, Coordinator...)", mr: "पद (Principal, Coordinator...)" },
  "Undergrad": { hi: "अंडरग्रेजुएट", mr: "अंडरग्रॅज्युएट" },
  "Priority WhatsApp support": { hi: "प्राथमिकता WhatsApp सपोर्ट", mr: "प्राधान्य WhatsApp सपोर्ट" },
  "School dashboard access": { hi: "स्कूल डैशबोर्ड एक्सेस", mr: "स्कूल डॅशबोर्ड अ‍ॅक्सेस" },
  "Reading, cricket, robotics club...": { hi: "रीडिंग, क्रिकेट, रोबोटिक्स क्लब...", mr: "वाचन, क्रिकेट, रोबोटिक्स क्लब..." },
  "We've noted your details. Expect a call/email from our team soon.": { hi: "हमने आपकी जानकारी नोट कर ली है। हमारी टीम जल्द ही आपसे कॉल/ईमेल के ज़रिए संपर्क करेगी।", mr: "आम्ही तुमचे तपशील नोंदवून घेतले आहेत. आमची टीम लवकरच तुमच्याशी कॉल/ईमेलद्वारे संपर्क करेल." },
  "Download PDF": { hi: "PDF डाउनलोड करें", mr: "PDF डाउनलोड करा" },
  "Fill the form below. Our team will reach out within 2 working days.": { hi: "नीचे दिया गया फॉर्म भरें। हमारी टीम 2 कार्यदिवसों में संपर्क करेगी।", mr: "खालील फॉर्म भरा. आमची टीम 2 कामकाजाच्या दिवसांत संपर्क करेल." },
  "Email *": { hi: "ईमेल *", mr: "ईमेल *" },
  "What you did, tools, outcome": { hi: "आपने क्या किया, टूल्स, परिणाम", mr: "तुम्ही काय केले, टूल्स, परिणाम" },
  "Psychometric Testing": { hi: "साइकोमेट्रिक टेस्टिंग", mr: "सायकोमेट्रिक टेस्टिंग" },
  "Psychometric test for all Class 9–12 students": { hi: "कक्षा 9–12 के सभी छात्रों के लिए साइकोमेट्रिक टेस्ट", mr: "इयत्ता 9–12 च्या सर्व विद्यार्थ्यांसाठी सायकोमेट्रिक टेस्ट" },
  "Everything your students need in one program": { hi: "आपके छात्रों के लिए आवश्यक सब कुछ एक ही प्रोग्राम में", mr: "तुमच्या विद्यार्थ्यांना आवश्यक सर्वकाही एकाच प्रोग्राममध्ये" },
  "Standard": { hi: "स्टैंडर्ड", mr: "स्टँडर्ड" },
  "Train your in-house teachers/coordinators to interpret reports and run 1:1 sessions.": { hi: "रिपोर्ट्स को समझने और 1:1 सेशन आयोजित करने के लिए अपने शिक्षकों/कोऑर्डिनेटर्स को प्रशिक्षित करें।", mr: "रिपोर्ट्स समजून घेण्यासाठी आणि 1:1 सेशन्स घेण्यासाठी तुमच्या शिक्षकांना/कॉर्डिनेटर्सना प्रशिक्षित करा." },
  "Free, no-login resume builder for school and college students. Fill the form, get a polished PDF. Saved on this device.": { hi: "स्कूल और कॉलेज के छात्रों के लिए मुफ़्त, बिना लॉगिन वाला रिज्यूमे बिल्डर। फॉर्म भरें, बेहतरीन PDF पाएं। इसी डिवाइस पर सेव।", mr: "शाळा आणि कॉलेजच्या विद्यार्थ्यांसाठी मोफत, लॉगिन नसलेला रेझ्युमे बिल्डर. फॉर्म भरा, उत्कृष्ट PDF मिळवा. याच डिव्हाइसवर सेव्ह." },
  "Email": { hi: "ईमेल", mr: "ईमेल" },
  "Most chosen": { hi: "सबसे ज्यादा चुना गया", mr: "सर्वाधिक पसंतीचे" },
  "Projects": { hi: "प्रोजेक्ट्स", mr: "प्रोजेक्ट्स" },
  "Resume Builder": { hi: "रिज्यूमे बिल्डर", mr: "रेझ्युमे बिल्डर" },
  "Entry role (0–2 yrs)": { hi: "एंट्री रोल (0–2 वर्ष)", mr: "एंट्री रोल (0–2 वर्षे)" },
  "AI-interpreted PDF reports": { hi: "AI-इंटरप्रिटेड PDF रिपोर्ट्स", mr: "AI-इंटरप्रिटेड PDF रिपोर्ट्स" },
  "Contact for pricing": { hi: "कीमत जानने के लिए संपर्क करें", mr: "किमतीसाठी संपर्क करा" },
  "Long term": { hi: "लॉन्ग टर्म", mr: "दीर्घकालीन" },
  "Junior associate": { hi: "जूनियर एसोसिएट", mr: "ज्युनिअर असोसिएट" },
  "Send request": { hi: "अनुरोध भेजें", mr: "विनंती पाठवा" },
  "Direct admission": { hi: "डायरेक्ट एडमिशन", mr: "डायरेक्ट अ‍ॅडमिशन" },
  "Counsellor Workshops": { hi: "काउंसलर वर्कशॉप्स", mr: "काउन्सिलर वर्कशॉप्स" },
  "Phone": { hi: "फ़ोन", mr: "फोन" },
  "On-campus or online sessions to align parents on the student's strengths and stream choice.": { hi: "विद्यार्थी की क्षमताओं और स्ट्रीम के चयन पर अभिभावकों के साथ तालमेल बनाने के लिए ऑन-कैंपस या ऑनलाइन सत्र।", mr: "विद्यार्थ्याची क्षमता आणि शाखा निवडीबाबत पालकांशी सुसंवाद साधण्यासाठी ऑन-कॅम्पस किंवा ऑनलाइन सत्रे." },
  "Anything specific to discuss?": { hi: "क्या किसी खास विषय पर चर्चा करनी है?", mr: "काही विशिष्ट विषयावर चर्चा करायची आहे का?" },
  "Book a demo": { hi: "डेमो बुक करें", mr: "डेमो बुक करा" },
  "Year-round access to our team for student queries, college choices and exam guidance.": { hi: "छात्रों के प्रश्नों, कॉलेज चयन और परीक्षा मार्गदर्शन के लिए साल भर हमारी टीम की सहायता।", mr: "विद्यार्थ्यांच्या शंका, कॉलेज निवड आणि परीक्षा मार्गदर्शनासाठी वर्षभर आमच्या टीमचे सहकार्य." },
  "Senior (8+ yrs)": { hi: "सीनियर (8+ वर्ष)", mr: "सिनिअर (8+ वर्षे)" },
  "Manage teams, own outcomes, mentor juniors.": { hi: "टीमों का प्रबंधन करें, परिणामों की ज़िम्मेदारी लें, जूनियर्स का मार्गदर्शन करें।", mr: "टीम्सचे व्यवस्थापन करा, निकालांची जबाबदारी घ्या, ज्युनिअर्सना मार्गदर्शन करा." },
  "Save draft": { hi: "ड्राफ़्ट सहेजें", mr: "ड्राफ्ट सेव्ह करा" },
  "School Dashboard": { hi: "स्कूल डैशबोर्ड", mr: "स्कूल डॅशबोर्ड" },
  "On-campus parent session": { hi: "ऑन-कैंपस अभिभावक सत्र", mr: "ऑन-कॅम्पस पालक सत्र" },
  "Cohort-level analytics: who needs intervention, popular streams, parent engagement.": { hi: "समूह-स्तरीय विश्लेषण: किसे सहायता की आवश्यकता है, लोकप्रिय स्ट्रीम्स, अभिभावकों की भागीदारी।", mr: "गट-स्तरीय विश्लेषण: कोणाला मदतीची गरज आहे, लोकप्रिय शाखा, पालकांचा सहभाग." },
  "Approx. student count (Class 6–12)": { hi: "अनुमानित छात्र संख्या (कक्षा 6–12)", mr: "अंदाजे विद्यार्थी संख्या (इयत्ता 6–12)" },
  "Year": { hi: "वर्ष", mr: "वर्ष" },
  "Most chosen — balanced impact.": { hi: "सबसे अधिक चुना गया — संतुलित प्रभाव।", mr: "सर्वाधिक पसंती — संतुलित प्रभाव." },
  "Basic Info": { hi: "बुनियादी जानकारी", mr: "मूलभूत माहिती" },
  "Sending...": { hi: "भेजा जा रहा है...", mr: "पाठवत आहे..." },
  "Mid-career (3–7 yrs)": { hi: "मिड-करियर (3–7 वर्ष)", mr: "मिड-करिअर (3–7 वर्षे)" },
  "Education": { hi: "शिक्षा", mr: "शिक्षण" },
  "Build Your Student Resume": { hi: "अपना स्टूडेंट रेज़्यूमे बनाएं", mr: "तुमचा स्टुडंट रेझ्युमे तयार करा" },
  "Achievements": { hi: "उपलब्धियां", mr: "उपलब्धी" },
  "See what's included": { hi: "देखें क्या-क्या शामिल है", mr: "यात काय समाविष्ट आहे ते पहा" },
  "Specialist": { hi: "विशेषज्ञ", mr: "तज्ज्ञ" },
  "Institution": { hi: "संस्थान", mr: "संस्था" },
  "Top picks": { hi: "टॉप पिक्स", mr: "टॉप पिक्स" },
  "Request sent. We'll be in touch within 2 working days.": { hi: "अनुरोध भेज दिया गया है। हम 2 कार्य दिवसों के भीतर आपसे संपर्क करेंगे।", mr: "विनंती पाठवली आहे. आम्ही 2 कामकाजाच्या दिवसांत तुमच्याशी संपर्क साधू." },
  "Flagship": { hi: "फ्लैगशिप", mr: "फ्लॅगशिप" },
  "Class 8–10": { hi: "कक्षा 8–10", mr: "इयत्ता 8–10" },
  "For Schools": { hi: "स्कूलों के लिए", mr: "शाळांसाठी" },
  "Qualification / Class": { hi: "योग्यता / कक्षा", mr: "पात्रता / इयत्ता" },
  "Full name": { hi: "पूरा नाम", mr: "पूर्ण नाव" },
  "HBK Careers partners with schools to deliver RIASEC + Multiple Intelligences + Aptitude testing, AI-interpreted reports, parent communication and counsellor training.": { hi: "HBK Careers स्कूलों के साथ मिलकर RIASEC + Multiple Intelligences + Aptitude टेस्टिंग, AI-विश्लेषित रिपोर्ट्स, अभिभावक संवाद और काउंसलर प्रशिक्षण प्रदान करता है।", mr: "HBK Careers शाळांसोबत भागीदारी करून RIASEC + Multiple Intelligences + Aptitude चाचण्या, AI-विश्लेषित अहवाल, पालक संवाद आणि समुपदेशक प्रशिक्षण प्रदान करते." },
  "Career Objective": { hi: "करियर उद्देश्य", mr: "करिअर उद्दिष्ट" },
  "Achievement": { hi: "उपलब्धि", mr: "उपलब्धी" },
  "Essentials": { hi: "एसेंशियल्स", mr: "एसेंशियल्स" },
  "School name *": { hi: "स्कूल का नाम *", mr: "शाळेचे नाव *" },
  "Project title": { hi: "प्रोजेक्ट का शीर्षक", mr: "प्रकल्पाचे शीर्षक" },
  "School name, contact name and email are required": { hi: "स्कूल का नाम, संपर्क व्यक्ति का नाम और ईमेल आवश्यक हैं", mr: "शाळेचे नाव, संपर्क व्यक्तीचे नाव आणि ईमेल आवश्यक आहेत" },
  "1:1 sessions for select students": { hi: "चुनिंदा छात्रों के लिए 1:1 सत्र", mr: "निवडक विद्यार्थ्यांसाठी 1:1 सत्रे" },
  "AI-Interpreted Reports": { hi: "AI-विश्लेषित रिपोर्ट्स", mr: "AI-विश्लेषित अहवाल" },
  "Build the basics": { hi: "बुनियादी समझ बनाएं", mr: "पाया मजबूत करा" },
  "Termly counsellor trainings": { hi: "प्रत्येक सत्र में काउंसलर प्रशिक्षण", mr: "प्रत्येक सत्रात समुपदेशक प्रशिक्षण" },
  "Year-round program with deep follow-through.": { hi: "गहन फॉलो-थ्रू के साथ साल भर चलने वाला कार्यक्रम।", mr: "सखोल पाठपुराव्यासह वर्षभराचा कार्यक्रम." },
  "Customised pricing based on student count and selected modules.": { hi: "छात्रों की संख्या और चुने गए मॉड्यूल्स के आधार पर अनुकूलित शुल्क।", mr: "विद्यार्थ्यांची संख्या आणि निवडलेल्या मॉड्यूल्सनुसार सानुकूलित शुल्क." },
  "Hobbies & Interests": { hi: "शौक और रुचियां", mr: "छंद आणि आवडी" },
  "Could not send. Please try again.": { hi: "भेजा नहीं जा सका। कृपया पुनः प्रयास करें।", mr: "पाठवता आले नाही. कृपया पुन्हा प्रयत्न करा." },
  "Counsellor workshop (1 day)": { hi: "काउंसलर कार्यशाला (1 दिन)", mr: "समुपदेशक कार्यशाळा (1 दिवस)" },
  "City": { hi: "शहर", mr: "शहर" },
  "Bring evidence-based career guidance to every student in your school.": { hi: "अपने स्कूल के प्रत्येक छात्र तक साक्ष्य-आधारित करियर मार्गदर्शन पहुंचाएं।", mr: "तुमच्या शाळेतील प्रत्येक विद्यार्थ्यापर्यंत पुराव्यांवर आधारित करिअर मार्गदर्शन पोहोचवा." },
  "Ongoing Support": { hi: "निरंतर सहयोग", mr: "सतत सहाय्य" },
  "A 2-3 line summary of who you are and what you want to do next.": { hi: "आप कौन हैं और आगे क्या करना चाहते हैं, इसका 2-3 पंक्तियों का सारांश।", mr: "तुम्ही कोण आहात आणि पुढे काय करू इच्छिता याचा 2-3 ओळींचा सारांश." },
  "Partnership Tiers": { hi: "साझेदारी के स्तर", mr: "भागीदारीचे स्तर" },
  "Context, year, scale": { hi: "संदर्भ, वर्ष, पैमाना", mr: "संदर्भ, वर्ष, प्रमाण" },
  "Grade / %": { hi: "ग्रेड / %", mr: "ग्रेड / %" },
  "Skills": { hi: "कौशल", mr: "कौशल्ये" },
  "For schools starting their career-guidance journey.": { hi: "उन स्कूलों के लिए जो अपनी करियर-मार्गदर्शन यात्रा शुरू कर रहे हैं।", mr: "अशा शाळांसाठी ज्या आपला करिअर-मार्गदर्शन प्रवास सुरू करत आहेत." },
  "Comma-separated: Python, public speaking, MS Excel...": { hi: "कॉमा से अलग करें: Python, public speaking, MS Excel...", mr: "स्वल्पविरामाने वेगळे करा: Python, public speaking, MS Excel..." },
  "Lead / Manager": { hi: "लीड / मैनेजर", mr: "लीड / मॅनेजर" },
  "Director / Founder / Consultant": { hi: "डायरेक्टर / फाउंडर / कंसल्टेंट", mr: "डायरेक्टर / फाउंडर / कन्सल्टंट" },
  "Each student gets a 20-page report explaining strengths, stream fit and recommended careers.": { hi: "प्रत्येक छात्र को 20-पेज की रिपोर्ट मिलती है जिसमें क्षमताएं, सही स्ट्रीम और अनुशंसित करियर की जानकारी होती है।", mr: "प्रत्येक विद्यार्थ्याला 20-पानांचा रिपोर्ट मिळतो ज्यामध्ये सामर्थ्य, योग्य स्ट्रीम आणि शिफारस केलेल्या करिअरची माहिती असते." },
  "1 parent session (online)": { hi: "1 अभिभावक सत्र (ऑनलाइन)", mr: "1 पालक सत्र (ऑनलाइन)" },
};
