// Curated, Gujarat-first scholarships catalogue. Static — edit this file to update.
export type Scholarship = {
  id: string;
  name: string;
  provider: string;
  scope: "Gujarat" | "National";
  level: ("Class 10" | "Class 11-12" | "UG" | "PG" | "Diploma")[];
  category: ("Merit" | "Need-based" | "SC/ST/OBC" | "Minority" | "Girls" | "Sports" | "Disability")[];
  amount: string;
  deadline: string; // typical month
  eligibility: string;
  website: string;
};

export const SCHOLARSHIPS: Scholarship[] = [
  {
    id: "mysy",
    name: "Mukhyamantri Yuva Swavalamban Yojana (MYSY)",
    provider: "Govt. of Gujarat",
    scope: "Gujarat",
    level: ["UG", "Diploma"],
    category: ["Merit", "Need-based"],
    amount: "Up to ₹2,00,000 tuition + ₹1,200/month hostel",
    deadline: "July–Sept (annual)",
    eligibility: "Class 12 with 80%+ (or Diploma 65%+), family income < ₹6 lakh",
    website: "mysy.guj.nic.in",
  },
  {
    id: "digital-gujarat",
    name: "Digital Gujarat Post-Matric Scholarship",
    provider: "Govt. of Gujarat",
    scope: "Gujarat",
    level: ["Class 11-12", "UG", "PG", "Diploma"],
    category: ["SC/ST/OBC", "Minority", "Need-based"],
    amount: "Tuition + maintenance allowance (varies)",
    deadline: "Aug–Nov (annual)",
    eligibility: "SC/ST/SEBC/OBC/Minority students of Gujarat, income criteria apply",
    website: "digitalgujarat.gov.in",
  },
  {
    id: "kanya-kelavani",
    name: "Kanya Kelavani / Vidya Lakshmi Bond",
    provider: "Govt. of Gujarat",
    scope: "Gujarat",
    level: ["Class 10"],
    category: ["Girls"],
    amount: "₹1,000 bond at Class 1, encashable on completing Class 12",
    deadline: "Class 1 enrolment drive",
    eligibility: "Girl students in govt./aided Gujarat schools",
    website: "education.gujarat.gov.in",
  },
  {
    id: "namo-saraswati",
    name: "Namo Saraswati Vigyan Sadhana Yojana",
    provider: "Govt. of Gujarat",
    scope: "Gujarat",
    level: ["Class 11-12"],
    category: ["Merit", "Need-based"],
    amount: "₹25,000 total (₹10k Class 11 + ₹15k Class 12)",
    deadline: "After Class 10 results (Jun–Jul)",
    eligibility: "Class 10 with 50%+, choosing Science stream, family income < ₹6 lakh",
    website: "education.gujarat.gov.in",
  },
  {
    id: "namo-lakshmi",
    name: "Namo Lakshmi Yojana",
    provider: "Govt. of Gujarat",
    scope: "Gujarat",
    level: ["Class 11-12"],
    category: ["Girls", "Need-based"],
    amount: "₹50,000 total across Class 9–12 for girls",
    deadline: "Annual",
    eligibility: "Girl students in govt./grant-in-aid schools, family income < ₹6 lakh",
    website: "education.gujarat.gov.in",
  },
  {
    id: "nmms",
    name: "National Means-cum-Merit Scholarship (NMMS)",
    provider: "MoE, Govt. of India",
    scope: "National",
    level: ["Class 11-12"],
    category: ["Merit", "Need-based"],
    amount: "₹12,000/year (Class 9 to 12)",
    deadline: "Exam in Nov, apply by Oct",
    eligibility: "Class 8 with 55%+, family income < ₹3.5 lakh, govt. school",
    website: "scholarships.gov.in",
  },
  {
    id: "inspire",
    name: "INSPIRE Scholarship for Higher Education (SHE)",
    provider: "DST, Govt. of India",
    scope: "National",
    level: ["UG"],
    category: ["Merit"],
    amount: "₹80,000/year (₹60k stipend + ₹20k summer project)",
    deadline: "July–Aug",
    eligibility: "Top 1% in Class 12 board, pursuing BSc/Integrated MSc in natural sciences",
    website: "online-inspire.gov.in",
  },
  {
    id: "kvpy",
    name: "PM Young Achievers Scholarship (PM-YASASVI)",
    provider: "MoSJE, Govt. of India",
    scope: "National",
    level: ["Class 11-12"],
    category: ["SC/ST/OBC"],
    amount: "₹75,000 – ₹1,25,000/year",
    deadline: "July–Aug",
    eligibility: "OBC/EBC/DNT students, family income < ₹2.5 lakh, Class 8/10 entrance test",
    website: "yet.nta.ac.in",
  },
  {
    id: "reliance-foundation",
    name: "Reliance Foundation Undergraduate Scholarships",
    provider: "Reliance Foundation",
    scope: "National",
    level: ["UG"],
    category: ["Merit", "Need-based"],
    amount: "Up to ₹2,00,000 total",
    deadline: "Sept–Oct",
    eligibility: "Class 12 with 60%+, family income < ₹15 lakh, 5,000 awardees/year",
    website: "scholarships.reliancefoundation.org",
  },
  {
    id: "tata-trusts",
    name: "Tata Trusts Education Grants",
    provider: "Tata Trusts",
    scope: "National",
    level: ["UG", "PG"],
    category: ["Need-based", "Merit"],
    amount: "Partial to full fees (case-based)",
    deadline: "Year-round (case review)",
    eligibility: "Indian students in recognised institutes, financial need",
    website: "tatatrusts.org",
  },
  {
    id: "aditya-birla",
    name: "Aditya Birla Scholarship",
    provider: "Aditya Birla Group",
    scope: "National",
    level: ["UG", "PG"],
    category: ["Merit"],
    amount: "Up to ₹1,80,000/year",
    deadline: "By invitation (top IITs/IIMs/BITS/NLS)",
    eligibility: "Selected top performers at premier institutes",
    website: "adityabirlascholars.net",
  },
  {
    id: "kc-mahindra",
    name: "K.C. Mahindra Scholarship for Post-Graduate Studies Abroad",
    provider: "K.C. Mahindra Education Trust",
    scope: "National",
    level: ["PG"],
    category: ["Merit"],
    amount: "Up to ₹10,00,000 (interest-free loan-scholarship)",
    deadline: "Mar–Apr",
    eligibility: "Indian students admitted to recognised foreign PG programs",
    website: "kcmet.org",
  },
  {
    id: "pragati",
    name: "AICTE Pragati Scholarship for Girls",
    provider: "AICTE",
    scope: "National",
    level: ["UG", "Diploma"],
    category: ["Girls"],
    amount: "₹50,000/year",
    deadline: "Sept–Nov",
    eligibility: "Girl students in AICTE-approved technical courses, family income < ₹8 lakh",
    website: "aicte-india.org",
  },
  {
    id: "saksham",
    name: "AICTE Saksham Scholarship for Disabled Students",
    provider: "AICTE",
    scope: "National",
    level: ["UG", "Diploma"],
    category: ["Disability"],
    amount: "₹50,000/year",
    deadline: "Sept–Nov",
    eligibility: "Differently-abled students (40%+) in AICTE-approved courses",
    website: "aicte-india.org",
  },
  {
    id: "maulana-azad",
    name: "Maulana Azad National Scholarship (Begum Hazrat Mahal)",
    provider: "Maulana Azad Education Foundation",
    scope: "National",
    level: ["Class 11-12"],
    category: ["Minority", "Girls"],
    amount: "₹5,000 – ₹12,000",
    deadline: "Aug–Oct",
    eligibility: "Girl students from minority communities (Class 9–12), 50%+ marks",
    website: "scholarships.gov.in",
  },
  {
    id: "khelo-india",
    name: "Khelo India Talent Scholarship",
    provider: "Ministry of Youth Affairs & Sports",
    scope: "National",
    level: ["Class 10", "Class 11-12", "UG"],
    category: ["Sports"],
    amount: "₹6,28,000/year (training + stipend)",
    deadline: "Selection via Khelo India Games",
    eligibility: "Selected athletes under Khelo India Talent Development Scheme",
    website: "kheloindia.gov.in",
  },
  {
    id: "loreal",
    name: "L'Oréal India 'For Young Women in Science' Scholarship",
    provider: "L'Oréal India",
    scope: "National",
    level: ["UG"],
    category: ["Girls", "Merit"],
    amount: "Up to ₹2,50,000",
    deadline: "Jul–Aug",
    eligibility: "Girls with 85%+ in Class 12 PCM/PCB, pursuing science UG, income < ₹6 lakh",
    website: "foryoungwomeninscience.com",
  },
  {
    id: "sitaram-jindal",
    name: "Sitaram Jindal Foundation Scholarship",
    provider: "Sitaram Jindal Foundation",
    scope: "National",
    level: ["Class 11-12", "UG", "PG", "Diploma"],
    category: ["Merit", "Need-based"],
    amount: "₹500 – ₹3,200/month",
    deadline: "Year-round",
    eligibility: "Various — by course, marks, family income",
    website: "sitaramjindalfoundation.org",
  },
];
