// Generated from the HBK Scholarships & Entrance Exams tracker. Static — edit to update.
export type Scholarship = {
  id: string;
  name: string;
  category: string;
  group: string;
  appliesTo: string;
  classLevel: string;
  levelGroup: string;
  whoFor: string;
  incomeLimit: string;
  amount: string;
  applyAt: string;
  /** Absolute official URL. Empty when the scheme is applied for through varying state portals. */
  applyUrl: string;
  window: string;
  priority: string;
  notes: string;
};

/** Schemes that are suspended or discontinued — never list these on the site. */
export const DO_NOT_CIRCULATE: { name: string; status: string; note: string }[] = [
  { name: "NTSE - National Talent Search Examination", status: "Suspended since 2021", note: "Still listed on aggregator sites; do not include in circulars" },
  { name: "KVPY", status: "Discontinued", note: "Merged into the INSPIRE scheme" },
  { name: "Begum Hazrat Mahal National Scholarship", status: "Discontinued", note: "MAEF scheme wound up" },
  { name: "Maulana Azad National Fellowship", status: "Discontinued", note: "" },
  { name: "Padho Pardesh", status: "Discontinued", note: "Interest subsidy scheme for minority students, withdrawn" },
  { name: "Merit-cum-Means for minorities (professional/technical)", status: "Discontinued", note: "" },
];

export const SCHOLARSHIP_PRIORITY_ORDER = ["Top priority", "High", "Medium", "Portal only", "Low", "Not applicable"];

export const SCHOLARSHIPS: Scholarship[] = [
  { id: "pre-matric-scholarship-for-sc-students", name: "Pre-Matric Scholarship for SC students", category: "Central - school", group: "Central", appliesTo: "All India", classLevel: "Class 9-10", levelGroup: "School (up to Class 10)", whoFor: "SC students", incomeLimit: "Scheme-wise", amount: "Scheme-wise", applyAt: "scholarships.gov.in", applyUrl: "https://scholarships.gov.in/", window: "Opened 1 Jun 2026; most schemes close 31 Oct 2026", priority: "High", notes: "OTR mandatory before applying" },
  { id: "pre-matric-scholarship-for-st-students", name: "Pre-Matric Scholarship for ST students", category: "Central - school", group: "Central", appliesTo: "All India", classLevel: "Class 9-10", levelGroup: "School (up to Class 10)", whoFor: "ST students", incomeLimit: "Scheme-wise", amount: "Scheme-wise", applyAt: "scholarships.gov.in", applyUrl: "https://scholarships.gov.in/", window: "Opened 1 Jun 2026; most close 31 Oct 2026", priority: "High", notes: "Key scheme for tribal cohorts" },
  { id: "pm-yasasvi-pre-matric", name: "PM YASASVI Pre-Matric", category: "Central - school", group: "Central", appliesTo: "All India", classLevel: "Class 9-10", levelGroup: "School (up to Class 10)", whoFor: "OBC, EBC, DNT", incomeLimit: "Up to Rs 2.5 lakh", amount: "Scheme-wise", applyAt: "scholarships.gov.in", applyUrl: "https://scholarships.gov.in/", window: "Opened 1 Jun 2026; most close 31 Oct 2026", priority: "High", notes: "" },
  { id: "pre-matric-scholarship-for-minority-students", name: "Pre-Matric Scholarship for Minority students", category: "Central - school", group: "Central", appliesTo: "All India", classLevel: "Class 9-10", levelGroup: "School (up to Class 10)", whoFor: "Notified minority communities", incomeLimit: "Scheme-wise", amount: "Scheme-wise", applyAt: "scholarships.gov.in", applyUrl: "https://scholarships.gov.in/", window: "Opened 1 Jun 2026", priority: "Medium", notes: "" },
  { id: "pre-matric-unclean-and-hazardous-occupations", name: "Pre-Matric - unclean and hazardous occupations", category: "Central - school", group: "Central", appliesTo: "All India", classLevel: "Class 1-10", levelGroup: "School (up to Class 10)", whoFor: "Children of parents in unclean/hazardous work", incomeLimit: "Scheme-wise", amount: "Scheme-wise", applyAt: "scholarships.gov.in", applyUrl: "https://scholarships.gov.in/", window: "Opened 1 Jun 2026", priority: "Medium", notes: "Covers Class 1 onward, unlike most pre-matric schemes" },
  { id: "pre-matric-for-students-with-disabilities-depwd", name: "Pre-Matric for Students with Disabilities (DEPwD)", category: "Central - school", group: "Central", appliesTo: "All India", classLevel: "Class 9-10", levelGroup: "School (up to Class 10)", whoFor: "Students with disabilities", incomeLimit: "Up to Rs 2.5 lakh", amount: "Scheme-wise", applyAt: "scholarships.gov.in", applyUrl: "https://scholarships.gov.in/", window: "Opened 1 Jun 2026", priority: "Medium", notes: "" },
  { id: "nmms-national-means-cum-merit-scholarship", name: "NMMS - National Means-cum-Merit Scholarship", category: "Central - merit exam", group: "Central", appliesTo: "All India", classLevel: "Class 8 exam", levelGroup: "School (up to Class 10)", whoFor: "Govt, local body and aided school students", incomeLimit: "Up to Rs 3.5 lakh", amount: "Rs 12,000/yr for Class 9-12", applyAt: "State SCERT portals", applyUrl: "", window: "Registration usually Aug-Sep; exam Nov-Dec", priority: "Top priority", notes: "Private, KV, Navodaya and Sainik students NOT eligible - maps exactly onto our schools" },
  { id: "ministry-of-labour-welfare-scholarships", name: "Ministry of Labour welfare scholarships", category: "Central - school", group: "Central", appliesTo: "All India", classLevel: "Class 1 onwards", levelGroup: "School (up to Class 10)", whoFor: "Children of beedi, cine and non-coal mine workers", incomeLimit: "Scheme-wise", amount: "Scheme-wise", applyAt: "scholarships.gov.in", applyUrl: "https://scholarships.gov.in/", window: "Opened 1 Jun 2026", priority: "Low", notes: "Can usually be combined with one merit scholarship" },
  { id: "pm-cares-for-children", name: "PM CARES for Children", category: "Central - school", group: "Central", appliesTo: "All India", classLevel: "School and higher", levelGroup: "School (up to Class 10)", whoFor: "Children who lost parents to COVID", incomeLimit: "", amount: "Scheme-wise", applyAt: "pmcaresforchildren.in", applyUrl: "https://pmcaresforchildren.in/", window: "Rolling", priority: "Low", notes: "" },
  { id: "eklavya-model-residential-schools-emrs", name: "Eklavya Model Residential Schools (EMRS)", category: "Central - residential", group: "Central", appliesTo: "All India", classLevel: "Class 6-12", levelGroup: "School (up to Class 10)", whoFor: "ST students", incomeLimit: "Scheme-wise", amount: "Free residential schooling", applyAt: "State tribal dept / EMRS portal", applyUrl: "https://emrs.tribal.gov.in/", window: "Admission cycle varies by state", priority: "High", notes: "Not a cash scholarship - full schooling support" },
  { id: "jawahar-navodaya-vidyalaya-selection-test", name: "Jawahar Navodaya Vidyalaya Selection Test", category: "Central - residential", group: "Central", appliesTo: "All India", classLevel: "Class 6 entry", levelGroup: "School (up to Class 10)", whoFor: "Rural students, all categories", incomeLimit: "", amount: "Free residential schooling", applyAt: "navodaya.gov.in", applyUrl: "https://navodaya.gov.in/", window: "Registration usually Jun-Sep", priority: "High", notes: "Strong option for Grade 5 students in our catchments" },
  { id: "sainik-school-admission-aissee", name: "Sainik School admission (AISSEE)", category: "Central - residential", group: "Central", appliesTo: "All India", classLevel: "Class 6 and 9 entry", levelGroup: "School (up to Class 10)", whoFor: "All, with category fee concessions", incomeLimit: "Concession by category", amount: "Fee concession", applyAt: "aissee.ntaonline.in", applyUrl: "https://sainikschoolsociety.in/", window: "Registration usually Dec-Jan", priority: "Low", notes: "" },
  { id: "khelo-india-athlete-scholarship", name: "Khelo India Athlete Scholarship", category: "Central - talent", group: "Central", appliesTo: "All India", classLevel: "School and above", levelGroup: "School (up to Class 10)", whoFor: "Identified young athletes", incomeLimit: "", amount: "Scheme-wise", applyAt: "kheloindia.gov.in", applyUrl: "https://kheloindia.gov.in/", window: "Rolling / selection based", priority: "Low", notes: "" },
  { id: "cbse-merit-scholarship-for-single-girl-child", name: "CBSE Merit Scholarship for Single Girl Child", category: "Central - merit", group: "Central", appliesTo: "All India", classLevel: "Class 11-12", levelGroup: "Class 11-12", whoFor: "Single girl child, CBSE Class 10 pass", incomeLimit: "", amount: "Scheme-wise", applyAt: "cbse.gov.in", applyUrl: "https://www.cbse.gov.in/", window: "Usually opens after Class 10 results", priority: "Low", notes: "CBSE schools only" },
  { id: "nios-fee-exemption", name: "NIOS fee exemption", category: "Central - school", group: "Central", appliesTo: "All India", classLevel: "Secondary / Sr secondary", levelGroup: "Class 11-12", whoFor: "SC, ST, PwD and girl students", incomeLimit: "", amount: "Fee waiver", applyAt: "nios.ac.in", applyUrl: "https://www.nios.ac.in/", window: "Per admission cycle", priority: "Low", notes: "Useful for dropouts re-entering education" },
  { id: "post-matric-scholarship-for-sc-students", name: "Post-Matric Scholarship for SC students", category: "Central - post-matric", group: "Central", appliesTo: "All India", classLevel: "Class 11 onwards", levelGroup: "Class 11-12", whoFor: "SC students", incomeLimit: "Scheme-wise", amount: "Scheme-wise", applyAt: "scholarships.gov.in / state portal", applyUrl: "https://scholarships.gov.in/", window: "Most close 31 Oct 2026", priority: "High", notes: "" },
  { id: "post-matric-scholarship-for-st-students", name: "Post-Matric Scholarship for ST students", category: "Central - post-matric", group: "Central", appliesTo: "All India", classLevel: "Class 11 onwards", levelGroup: "Class 11-12", whoFor: "ST students", incomeLimit: "Scheme-wise", amount: "Scheme-wise", applyAt: "scholarships.gov.in / state portal", applyUrl: "https://scholarships.gov.in/", window: "Most close 31 Oct 2026", priority: "High", notes: "" },
  { id: "pm-yasasvi-post-matric", name: "PM YASASVI Post-Matric", category: "Central - post-matric", group: "Central", appliesTo: "All India", classLevel: "Class 11 onwards", levelGroup: "Class 11-12", whoFor: "OBC, EBC, DNT", incomeLimit: "Up to Rs 2.5 lakh", amount: "Scheme-wise", applyAt: "scholarships.gov.in", applyUrl: "https://scholarships.gov.in/", window: "Most close 31 Oct 2026", priority: "High", notes: "" },
  { id: "post-matric-scholarship-for-minority-students", name: "Post-Matric Scholarship for Minority students", category: "Central - post-matric", group: "Central", appliesTo: "All India", classLevel: "Class 11 onwards", levelGroup: "Class 11-12", whoFor: "Notified minority communities", incomeLimit: "Scheme-wise", amount: "Scheme-wise", applyAt: "scholarships.gov.in", applyUrl: "https://scholarships.gov.in/", window: "Most close 31 Oct 2026", priority: "Medium", notes: "" },
  { id: "post-matric-for-students-with-disabilities", name: "Post-Matric for Students with Disabilities", category: "Central - post-matric", group: "Central", appliesTo: "All India", classLevel: "Class 11 onwards", levelGroup: "Class 11-12", whoFor: "Students with disabilities", incomeLimit: "Up to Rs 2.5 lakh", amount: "Scheme-wise", applyAt: "scholarships.gov.in", applyUrl: "https://scholarships.gov.in/", window: "Most close 31 Oct 2026", priority: "Medium", notes: "" },
  { id: "pm-usp-central-sector-scheme-csss", name: "PM-USP Central Sector Scheme (CSSS)", category: "Central - merit", group: "Central", appliesTo: "All India", classLevel: "UG / PG", levelGroup: "PG / research", whoFor: "Top Class 12 performers", incomeLimit: "Scheme-wise", amount: "Scheme-wise", applyAt: "scholarships.gov.in", applyUrl: "https://scholarships.gov.in/", window: "Closes 30 Sep 2026 - EARLIER than other schemes", priority: "High", notes: "Diarise separately; students miss it because they assume 31 Oct" },
  { id: "top-class-education-for-sc-students", name: "Top Class Education for SC students", category: "Central - higher", group: "Central", appliesTo: "All India", classLevel: "UG / PG", levelGroup: "PG / research", whoFor: "SC students in notified institutions", incomeLimit: "Up to Rs 8 lakh", amount: "Full fee + allowances", applyAt: "scholarships.gov.in", applyUrl: "https://scholarships.gov.in/", window: "Per cycle", priority: "Medium", notes: "" },
  { id: "top-class-education-for-st-students", name: "Top Class Education for ST students", category: "Central - higher", group: "Central", appliesTo: "All India", classLevel: "UG / PG", levelGroup: "PG / research", whoFor: "ST students in notified institutions", incomeLimit: "Scheme-wise", amount: "Full fee + allowances", applyAt: "scholarships.gov.in", applyUrl: "https://scholarships.gov.in/", window: "Per cycle", priority: "Medium", notes: "" },
  { id: "national-overseas-scholarship-sc", name: "National Overseas Scholarship - SC", category: "Central - overseas", group: "Central", appliesTo: "All India", classLevel: "Masters / PhD abroad", levelGroup: "PG / research", whoFor: "SC, denotified and landless labourer families", incomeLimit: "Scheme-wise", amount: "Full funding", applyAt: "socialjustice.gov.in", applyUrl: "https://socialjustice.gov.in/", window: "Annual cycle", priority: "Low", notes: "" },
  { id: "national-overseas-scholarship-st", name: "National Overseas Scholarship - ST", category: "Central - overseas", group: "Central", appliesTo: "All India", classLevel: "Masters / PhD abroad", levelGroup: "PG / research", whoFor: "ST students", incomeLimit: "Scheme-wise", amount: "Full funding", applyAt: "tribal.nic.in", applyUrl: "https://tribal.nic.in/", window: "Annual cycle", priority: "Low", notes: "" },
  { id: "national-fellowship-for-sc-students", name: "National Fellowship for SC students", category: "Central - research", group: "Central", appliesTo: "All India", classLevel: "MPhil / PhD", levelGroup: "PG / research", whoFor: "SC research scholars", incomeLimit: "", amount: "Monthly fellowship", applyAt: "scholarships.gov.in / UGC", applyUrl: "https://scholarships.gov.in/", window: "Annual cycle", priority: "Low", notes: "" },
  { id: "national-fellowship-for-st-students", name: "National Fellowship for ST students", category: "Central - research", group: "Central", appliesTo: "All India", classLevel: "MPhil / PhD", levelGroup: "PG / research", whoFor: "ST research scholars", incomeLimit: "", amount: "Monthly fellowship", applyAt: "scholarships.gov.in / UGC", applyUrl: "https://scholarships.gov.in/", window: "Annual cycle", priority: "Low", notes: "" },
  { id: "ishan-uday", name: "Ishan Uday", category: "Central - higher", group: "Central", appliesTo: "North East", classLevel: "UG", levelGroup: "UG / diploma", whoFor: "North Eastern region students", incomeLimit: "Scheme-wise", amount: "Scheme-wise", applyAt: "UGC / scholarships.gov.in", applyUrl: "https://scholarships.gov.in/", window: "Annual cycle", priority: "Not applicable", notes: "Region-restricted" },
  { id: "nec-merit-scholarship", name: "NEC Merit Scholarship", category: "Central - higher", group: "Central", appliesTo: "North East", classLevel: "Class 11 onwards", levelGroup: "Class 11-12", whoFor: "North Eastern region students", incomeLimit: "Up to Rs 8 lakh", amount: "Scheme-wise", applyAt: "scholarships.gov.in", applyUrl: "https://scholarships.gov.in/", window: "Annual cycle", priority: "Not applicable", notes: "Region-restricted" },
  { id: "central-sector-interest-subsidy-csis", name: "Central Sector Interest Subsidy (CSIS)", category: "Central - loan support", group: "Central", appliesTo: "All India", classLevel: "Professional / technical UG-PG", levelGroup: "PG / research", whoFor: "Education loan holders", incomeLimit: "Up to Rs 4.5 lakh", amount: "Interest subsidy during moratorium", applyAt: "Via lending bank / Vidya Lakshmi", applyUrl: "https://www.vidyalakshmi.co.in/", window: "Rolling", priority: "Medium", notes: "Loan support, not a grant" },
  { id: "aicte-pragati", name: "AICTE Pragati", category: "Technical / vocational", group: "Technical / vocational", appliesTo: "All India", classLevel: "Diploma / degree technical", levelGroup: "UG / diploma", whoFor: "Girls in AICTE-approved institutions", incomeLimit: "Up to Rs 8 lakh", amount: "Approx Rs 50,000/yr", applyAt: "aicte-india.org / NSP", applyUrl: "https://www.aicte-india.org/schemes/students-development-schemes", window: "Annual cycle", priority: "High", notes: "Direct fit for UDYAM girls entering technical streams" },
  { id: "aicte-saksham", name: "AICTE Saksham", category: "Technical / vocational", group: "Technical / vocational", appliesTo: "All India", classLevel: "Diploma / degree technical", levelGroup: "UG / diploma", whoFor: "Students with 40%+ disability", incomeLimit: "Up to Rs 8 lakh", amount: "Approx Rs 50,000/yr", applyAt: "aicte-india.org / NSP", applyUrl: "https://www.aicte-india.org/schemes/students-development-schemes", window: "Annual cycle", priority: "Medium", notes: "" },
  { id: "aicte-swanath", name: "AICTE Swanath", category: "Technical / vocational", group: "Technical / vocational", appliesTo: "All India", classLevel: "Diploma / degree technical", levelGroup: "UG / diploma", whoFor: "Orphans, wards of martyrs, COVID-affected", incomeLimit: "Up to Rs 8 lakh", amount: "Scheme-wise", applyAt: "aicte-india.org / NSP", applyUrl: "https://www.aicte-india.org/schemes/students-development-schemes", window: "Annual cycle", priority: "Medium", notes: "" },
  { id: "inspire-she", name: "INSPIRE-SHE", category: "Technical / merit", group: "Technical / vocational", appliesTo: "All India", classLevel: "Science UG", levelGroup: "UG / diploma", whoFor: "Top Class 12 science performers", incomeLimit: "", amount: "Approx Rs 80,000/yr", applyAt: "online-inspire.gov.in", applyUrl: "https://online-inspire.gov.in/", window: "Annual cycle", priority: "Medium", notes: "" },
  { id: "prime-minister-s-research-fellowship-pmrf", name: "Prime Minister's Research Fellowship (PMRF)", category: "Research", group: "Research", appliesTo: "All India", classLevel: "PhD", levelGroup: "PG / research", whoFor: "Research scholars", incomeLimit: "", amount: "Monthly fellowship", applyAt: "pmrf.in", applyUrl: "https://pmrf.in/", window: "Two cycles a year", priority: "Low", notes: "" },
  { id: "pmsss-j-k-and-ladakh", name: "PMSSS - J&K and Ladakh", category: "Central - higher", group: "Central", appliesTo: "J&K / Ladakh", classLevel: "UG", levelGroup: "UG / diploma", whoFor: "J&K and Ladakh domicile students", incomeLimit: "Scheme-wise", amount: "Fee + maintenance", applyAt: "aicte-jk-scholarship.nic.in", applyUrl: "https://www.aicte-jk-scholarship-gov.in/", window: "Annual cycle", priority: "Not applicable", notes: "Region-restricted" },
  { id: "pmss-wards-of-ex-servicemen-and-police", name: "PMSS - wards of ex-servicemen and police", category: "Central - higher", group: "Central", appliesTo: "All India", classLevel: "Professional UG", levelGroup: "UG / diploma", whoFor: "Wards of ex-servicemen, police personnel", incomeLimit: "", amount: "Monthly scholarship", applyAt: "ksb.gov.in", applyUrl: "https://ksb.gov.in/", window: "Annual cycle", priority: "Low", notes: "" },
  { id: "craftsman-training-scheme-stipend", name: "Craftsman Training Scheme stipend", category: "Vocational", group: "Vocational", appliesTo: "Maharashtra", classLevel: "ITI trainees", levelGroup: "School (up to Class 10)", whoFor: "Trainees in government ITIs", incomeLimit: "Scheme-wise", amount: "Rs 500/month", applyAt: "MahaDBT", applyUrl: "https://mahadbt.maharashtra.gov.in/Login/Login", window: "Per training year", priority: "High", notes: "Relevant to Vocational track placements into ITIs" },
  { id: "vocational-training-fee-reimbursement", name: "Vocational training fee reimbursement", category: "Vocational", group: "Vocational", appliesTo: "Maharashtra", classLevel: "Vocational courses", levelGroup: "School (up to Class 10)", whoFor: "Backward class and open category students", incomeLimit: "Scheme-wise", amount: "Fee reimbursement", applyAt: "MahaDBT", applyUrl: "https://mahadbt.maharashtra.gov.in/Login/Login", window: "Per academic year", priority: "High", notes: "" },
  { id: "free-coaching-schemes-for-sc-and-obc", name: "Free coaching schemes for SC and OBC", category: "Central - coaching", group: "Central", appliesTo: "All India", classLevel: "Post Class 12", levelGroup: "School (up to Class 10)", whoFor: "SC and OBC students", incomeLimit: "Scheme-wise", amount: "Free coaching + monthly stipend", applyAt: "socialjustice.gov.in", applyUrl: "https://socialjustice.gov.in/", window: "Annual cycle", priority: "Medium", notes: "Covers UPSC, JEE, NEET, CAT, CLAT, SSC" },
  { id: "cm-gyan-sadhana-merit-scholarship-cgms", name: "CM Gyan Sadhana Merit Scholarship (CGMS)", category: "State - merit exam", group: "State", appliesTo: "Gujarat", classLevel: "Class 8 exam, pays Class 9-12", levelGroup: "School (up to Class 10)", whoFor: "Class 1-8 unbroken in govt, aided or RTE 12(1)(c) seat", incomeLimit: "Rs 1.2 lakh rural / Rs 1.5 lakh urban", amount: "Rs 20,000/yr Class 9-10; Rs 25,000/yr Class 11-12", applyAt: "sebexam.org / gssyguj.in", applyUrl: "https://www.sebexam.org/", window: "Registration usually Feb; exam around Apr", priority: "Top priority", notes: "25,000 awards a year; MAT 40 + SAT 80 marks; exam in Gujarati and English" },
  { id: "gyan-setu-merit-scholarship", name: "Gyan Setu Merit Scholarship", category: "State - merit exam", group: "State", appliesTo: "Gujarat", classLevel: "Class 5 and Class 8 entry", levelGroup: "School (up to Class 10)", whoFor: "Government and aided school students", incomeLimit: "Scheme-wise", amount: "Scheme-wise", applyAt: "sebexam.org", applyUrl: "https://www.sebexam.org/", window: "Registration usually Feb", priority: "High", notes: "" },
  { id: "pre-upper-primary-scholarship-exam-pup", name: "Pre-Upper Primary Scholarship Exam (PUP)", category: "State - merit exam", group: "State", appliesTo: "Maharashtra", classLevel: "Class 5", levelGroup: "School (up to Class 10)", whoFor: "Government and aided school students", incomeLimit: "", amount: "State scholarship", applyAt: "MSCE Pune", applyUrl: "https://www.mscepune.in/", window: "Registration usually Oct-Nov; exam Feb", priority: "Top priority", notes: "Direct fit for BMC schools" },
  { id: "pre-secondary-scholarship-exam-pss", name: "Pre-Secondary Scholarship Exam (PSS)", category: "State - merit exam", group: "State", appliesTo: "Maharashtra", classLevel: "Class 8", levelGroup: "School (up to Class 10)", whoFor: "Government and aided school students", incomeLimit: "", amount: "State scholarship", applyAt: "MSCE Pune", applyUrl: "https://www.mscepune.in/", window: "Registration usually Oct-Nov; exam Feb", priority: "Top priority", notes: "Direct fit for BMC schools" },
  { id: "aakash-anthe", name: "Aakash ANTHE", category: "Private - talent test", group: "Private", appliesTo: "All India", classLevel: "Class 7-12", levelGroup: "School (up to Class 10)", whoFor: "All students", incomeLimit: "", amount: "Fee waiver up to 100%", applyAt: "aakash.ac.in", applyUrl: "https://anthe.aakash.ac.in/", window: "Usually Sep-Oct", priority: "Medium", notes: "Coaching fee waiver, not cash" },
  { id: "allen-tallentex", name: "Allen TALLENTEX", category: "Private - talent test", group: "Private", appliesTo: "All India", classLevel: "Class 5-11", levelGroup: "Class 11-12", whoFor: "All students", incomeLimit: "", amount: "Cash award + fee waiver", applyAt: "tallentex.com", applyUrl: "https://www.tallentex.com/", window: "Usually Sep-Nov", priority: "Medium", notes: "" },
  { id: "pw-scholarship-admission-test-pwsat", name: "PW Scholarship Admission Test (PWSAT)", category: "Private - talent test", group: "Private", appliesTo: "All India", classLevel: "Class 6-12", levelGroup: "School (up to Class 10)", whoFor: "All students", incomeLimit: "", amount: "Up to 90% fee waiver", applyAt: "pw.live", applyUrl: "https://www.pw.live/", window: "Multiple phases a year", priority: "Medium", notes: "" },
  { id: "agnipankh-scholarship-exam", name: "Agnipankh Scholarship Exam", category: "Private - talent test", group: "Private", appliesTo: "All India", classLevel: "Class 1-10", levelGroup: "School (up to Class 10)", whoFor: "All students", incomeLimit: "", amount: "Merit scholarship", applyAt: "Organiser portal", applyUrl: "https://www.agnipankh.in/", window: "Annual cycle", priority: "Low", notes: "" },
  { id: "digital-gujarat-pre-matric-sc", name: "Digital Gujarat Pre-Matric SC", category: "State - Gujarat", group: "State", appliesTo: "Gujarat", classLevel: "Class 1-10", levelGroup: "School (up to Class 10)", whoFor: "SC students", incomeLimit: "Scheme-wise", amount: "Scheme-wise", applyAt: "digitalgujarat.gov.in", applyUrl: "https://www.digitalgujarat.gov.in/", window: "Pre-matric window usually closes end Aug", priority: "High", notes: "" },
  { id: "digital-gujarat-pre-matric-st", name: "Digital Gujarat Pre-Matric ST", category: "State - Gujarat", group: "State", appliesTo: "Gujarat", classLevel: "Class 1-10", levelGroup: "School (up to Class 10)", whoFor: "ST students", incomeLimit: "Scheme-wise", amount: "Scheme-wise", applyAt: "digitalgujarat.gov.in", applyUrl: "https://www.digitalgujarat.gov.in/", window: "Pre-matric window usually closes end Aug", priority: "High", notes: "" },
  { id: "bck-6-1-post-matric-sc-central", name: "BCK-6.1 Post-Matric SC (central)", category: "State - Gujarat", group: "State", appliesTo: "Gujarat", classLevel: "Class 11 onwards", levelGroup: "Class 11-12", whoFor: "SC students", incomeLimit: "Up to Rs 2.5 lakh", amount: "Scheme-wise", applyAt: "gssp.gujarat.gov.in", applyUrl: "https://www.digitalgujarat.gov.in/", window: "6 Jul - 30 Sep 2026", priority: "High", notes: "Income up to Rs 2.5L must use this, not the state scheme" },
  { id: "bck-5-bck-5a-state-post-matric-sc", name: "BCK-5 / BCK-5A State Post-Matric SC", category: "State - Gujarat", group: "State", appliesTo: "Gujarat", classLevel: "Class 11 onwards", levelGroup: "Class 11-12", whoFor: "SC students above central income limit", incomeLimit: "Above Rs 2.5 lakh", amount: "Scheme-wise", applyAt: "gssp.gujarat.gov.in", applyUrl: "https://www.digitalgujarat.gov.in/", window: "6 Jul - 30 Sep 2026", priority: "High", notes: "Wrong scheme choice costs the student the full amount later" },
  { id: "bck-78-developing-caste-post-matric", name: "BCK-78 Developing Caste Post-Matric", category: "State - Gujarat", group: "State", appliesTo: "Gujarat", classLevel: "Class 11 onwards", levelGroup: "Class 11-12", whoFor: "SEBC, OBC, EBC, NT-DNT, Minority", incomeLimit: "Scheme-wise", amount: "Scheme-wise", applyAt: "gssp.gujarat.gov.in", applyUrl: "https://www.digitalgujarat.gov.in/", window: "6 Jul - 30 Sep 2026", priority: "High", notes: "" },
  { id: "vky-8-st-post-matric", name: "VKY-8 ST Post-Matric", category: "State - Gujarat", group: "State", appliesTo: "Gujarat", classLevel: "Class 11 onwards", levelGroup: "Class 11-12", whoFor: "ST students", incomeLimit: "Up to Rs 2.5 lakh", amount: "Scheme-wise", applyAt: "gssp.gujarat.gov.in", applyUrl: "https://www.digitalgujarat.gov.in/", window: "1 Sep - 30 Nov 2026", priority: "High", notes: "ST window is separate and later than SC/OBC" },
  { id: "mysy-mukhyamantri-yuva-swavalamban-yojana", name: "MYSY - Mukhyamantri Yuva Swavalamban Yojana", category: "State - Gujarat", group: "State", appliesTo: "Gujarat", classLevel: "Diploma / degree", levelGroup: "UG / diploma", whoFor: "Class 10 and 12 merit students", incomeLimit: "Scheme-wise", amount: "Tuition, hostel and book assistance", applyAt: "mysy.guj.nic.in", applyUrl: "https://mysy.guj.nic.in/", window: "Annual cycle", priority: "High", notes: "" },
  { id: "instrumental-assistance", name: "Instrumental assistance", category: "State - Gujarat", group: "State", appliesTo: "Gujarat", classLevel: "Professional courses", levelGroup: "UG / diploma", whoFor: "SEBC and SC students", incomeLimit: "Scheme-wise", amount: "Rs 10,000 medical / Rs 5,000 engineering / Rs 3,000 diploma; Rs 3,000 one-time for SC", applyAt: "digitalgujarat.gov.in", applyUrl: "https://www.digitalgujarat.gov.in/", window: "With post-matric cycle", priority: "Medium", notes: "" },
  { id: "saraswati-sadhana-yojana", name: "Saraswati Sadhana Yojana", category: "State - Gujarat", group: "State", appliesTo: "Gujarat", classLevel: "Class 9 entry", levelGroup: "School (up to Class 10)", whoFor: "SC and ST girls", incomeLimit: "Scheme-wise", amount: "Free bicycle", applyAt: "District social welfare office", applyUrl: "https://www.digitalgujarat.gov.in/", window: "Start of academic year", priority: "Medium", notes: "Good retention lever for girls in Anjar and Kalol" },
  { id: "hostel-and-food-bill-assistance", name: "Hostel and food bill assistance", category: "State - Gujarat", group: "State", appliesTo: "Gujarat", classLevel: "Class 9 onwards", levelGroup: "School (up to Class 10)", whoFor: "SC and ST hostellers", incomeLimit: "Scheme-wise", amount: "Maintenance assistance", applyAt: "digitalgujarat.gov.in", applyUrl: "https://www.digitalgujarat.gov.in/", window: "Annual cycle", priority: "Medium", notes: "" },
  { id: "post-ssc-scholarship-for-girls", name: "Post-SSC scholarship for girls", category: "State - Gujarat", group: "State", appliesTo: "Gujarat", classLevel: "Class 11 onwards", levelGroup: "Class 11-12", whoFor: "Girl students", incomeLimit: "Scheme-wise", amount: "Scheme-wise", applyAt: "digitalgujarat.gov.in", applyUrl: "https://www.digitalgujarat.gov.in/", window: "Annual cycle", priority: "Medium", notes: "" },
  { id: "adijati-vikas-ashram-shala-and-hostel-support", name: "Adijati Vikas ashram shala and hostel support", category: "State - Gujarat", group: "State", appliesTo: "Gujarat", classLevel: "Class 1-12", levelGroup: "School (up to Class 10)", whoFor: "ST students", incomeLimit: "Scheme-wise", amount: "Residential support", applyAt: "Tribal Development Dept, Gujarat", applyUrl: "https://adijativikas.gujarat.gov.in/", window: "Rolling", priority: "Medium", notes: "" },
  { id: "savitribai-phule-scholarship-sc-girls", name: "Savitribai Phule Scholarship - SC girls", category: "State - Maharashtra", group: "State", appliesTo: "Maharashtra", classLevel: "Class 5-10", levelGroup: "School (up to Class 10)", whoFor: "SC girl students", incomeLimit: "Scheme-wise", amount: "Scheme-wise", applyAt: "MahaDBT 2.0", applyUrl: "https://mahadbt.maharashtra.gov.in/Login/Login", window: "Opened 1 Jun 2026", priority: "High", notes: "Strong fit for BMC girls' cohort" },
  { id: "savitribai-phule-scholarship-vjnt-sbc-girls", name: "Savitribai Phule Scholarship - VJNT / SBC girls", category: "State - Maharashtra", group: "State", appliesTo: "Maharashtra", classLevel: "Class 5-10", levelGroup: "School (up to Class 10)", whoFor: "VJNT and SBC girl students", incomeLimit: "Scheme-wise", amount: "Scheme-wise", applyAt: "MahaDBT 2.0", applyUrl: "https://mahadbt.maharashtra.gov.in/Login/Login", window: "Opened 1 Jun 2026", priority: "High", notes: "" },
  { id: "government-of-india-scholarship-for-class-9-and-10", name: "Government of India Scholarship for Class 9 and 10", category: "State - Maharashtra", group: "State", appliesTo: "Maharashtra", classLevel: "Class 9-10", levelGroup: "School (up to Class 10)", whoFor: "Category students per scheme", incomeLimit: "Scheme-wise", amount: "Scheme-wise", applyAt: "MahaDBT 2.0", applyUrl: "https://mahadbt.maharashtra.gov.in/Login/Login", window: "Opened 1 Jun 2026", priority: "High", notes: "" },
  { id: "bihar-student-credit-card", name: "Bihar Student Credit Card", category: "State - education loan", group: "State", appliesTo: "Bihar", classLevel: "After Class 12", levelGroup: "Undergraduate", whoFor: "Bihar students entering higher education", incomeLimit: "No income bar", amount: "Interest-free loan up to Rs 4 lakh", applyAt: "7nishchay-yuvaupmission.bihar.gov.in", applyUrl: "https://www.7nishchay-yuvaupmission.bihar.gov.in/", window: "Rolling", priority: "Portal only", notes: "Education loan scheme, not a scholarship" },
  { id: "rajarshi-chhatrapati-shahu-maharaj-merit-scholarship", name: "Rajarshi Chhatrapati Shahu Maharaj Merit Scholarship", category: "State - Maharashtra", group: "State", appliesTo: "Maharashtra", classLevel: "Class 11-12", levelGroup: "Class 11-12", whoFor: "SC merit students", incomeLimit: "Scheme-wise", amount: "Scheme-wise", applyAt: "MahaDBT 2.0", applyUrl: "https://mahadbt.maharashtra.gov.in/Login/Login", window: "Annual cycle", priority: "Medium", notes: "" },
  { id: "rajarshi-shahu-maharaj-shikshan-shulk-shishyavrutti-ebc", name: "Rajarshi Shahu Maharaj Shikshan Shulk Shishyavrutti (EBC)", category: "State - Maharashtra", group: "State", appliesTo: "Maharashtra", classLevel: "UG / professional", levelGroup: "UG / diploma", whoFor: "EBC students", incomeLimit: "Scheme-wise", amount: "Fee scholarship", applyAt: "MahaDBT 2.0", applyUrl: "https://mahadbt.maharashtra.gov.in/Login/Login", window: "Annual cycle", priority: "Medium", notes: "" },
  { id: "dr-panjabrao-deshmukh-hostel-maintenance-allowance", name: "Dr. Panjabrao Deshmukh hostel maintenance allowance", category: "State - Maharashtra", group: "State", appliesTo: "Maharashtra", classLevel: "UG / professional", levelGroup: "UG / diploma", whoFor: "Hostellers, incl. farmer and labourer families", incomeLimit: "Scheme-wise", amount: "Maintenance allowance", applyAt: "MahaDBT 2.0", applyUrl: "https://mahadbt.maharashtra.gov.in/Login/Login", window: "Annual cycle", priority: "Medium", notes: "" },
  { id: "post-matric-tuition-and-exam-fee-freeship-sc", name: "Post-Matric Tuition and Exam Fee Freeship (SC)", category: "State - Maharashtra", group: "State", appliesTo: "Maharashtra", classLevel: "Class 11 onwards", levelGroup: "Class 11-12", whoFor: "SC students", incomeLimit: "Scheme-wise", amount: "Fee freeship", applyAt: "MahaDBT 2.0", applyUrl: "https://mahadbt.maharashtra.gov.in/Login/Login", window: "Annual cycle", priority: "High", notes: "" },
  { id: "maintenance-allowance-sainik-school-students", name: "Maintenance allowance - Sainik school students", category: "State - Maharashtra", group: "State", appliesTo: "Maharashtra", classLevel: "School", levelGroup: "School (up to Class 10)", whoFor: "Sainik school students", incomeLimit: "Scheme-wise", amount: "Maintenance allowance", applyAt: "MahaDBT 2.0", applyUrl: "https://mahadbt.maharashtra.gov.in/Login/Login", window: "Annual cycle", priority: "Low", notes: "" },
  { id: "minority-scholarship-for-higher-and-professional-courses", name: "Minority scholarship for higher and professional courses", category: "State - Maharashtra", group: "State", appliesTo: "Maharashtra", classLevel: "UG / professional", levelGroup: "UG / diploma", whoFor: "Minority community students", incomeLimit: "Scheme-wise", amount: "Scheme-wise", applyAt: "MahaDBT 2.0", applyUrl: "https://mahadbt.maharashtra.gov.in/Login/Login", window: "Annual cycle", priority: "Medium", notes: "" },
  { id: "up-scholarship-pre-and-post-matric", name: "UP Scholarship - pre and post matric", category: "State - other", group: "State", appliesTo: "Uttar Pradesh", classLevel: "Class 9 onwards", levelGroup: "School (up to Class 10)", whoFor: "Category and income based", incomeLimit: "Scheme-wise", amount: "Scheme-wise", applyAt: "scholarship.up.gov.in", applyUrl: "https://scholarship.up.gov.in/", window: "Usually Jul-Dec", priority: "Portal only", notes: "For national rollout of the career portal" },
  { id: "bihar-mukhyamantri-kanya-utthan-yojana", name: "Bihar Mukhyamantri Kanya Utthan Yojana", category: "State - other", group: "State", appliesTo: "Bihar", classLevel: "Class 12 onwards", levelGroup: "Class 11-12", whoFor: "Girls of Bihar", incomeLimit: "No income bar", amount: "Stage-wise cash incentive", applyAt: "medhasoft.bih.nic.in", applyUrl: "https://medhasoft.bih.nic.in/", window: "Rolling", priority: "Portal only", notes: "" },
  { id: "mp-vikramaditya-and-gaon-ki-beti", name: "MP Vikramaditya and Gaon Ki Beti", category: "State - other", group: "State", appliesTo: "Madhya Pradesh", classLevel: "UG", levelGroup: "UG / diploma", whoFor: "Merit students; rural girls", incomeLimit: "Scheme-wise", amount: "Scheme-wise", applyAt: "scholarshipportal.mp.nic.in", applyUrl: "https://scholarshipportal.mp.nic.in/", window: "Annual cycle", priority: "Portal only", notes: "" },
  { id: "rajasthan-mukhyamantri-uchch-shiksha-chhatravriti", name: "Rajasthan Mukhyamantri Uchch Shiksha Chhatravriti", category: "State - other", group: "State", appliesTo: "Rajasthan", classLevel: "UG", levelGroup: "UG / diploma", whoFor: "Merit and income based", incomeLimit: "Scheme-wise", amount: "Scheme-wise", applyAt: "hte.rajasthan.gov.in", applyUrl: "https://hte.rajasthan.gov.in/", window: "Annual cycle", priority: "Portal only", notes: "" },
  { id: "karnataka-state-scholarship-portal-ssp", name: "Karnataka State Scholarship Portal (SSP)", category: "State - other", group: "State", appliesTo: "Karnataka", classLevel: "Class 1 onwards", levelGroup: "School (up to Class 10)", whoFor: "All notified categories", incomeLimit: "Scheme-wise", amount: "Scheme-wise", applyAt: "ssp.postmatric.karnataka.gov.in", applyUrl: "https://ssp.postmatric.karnataka.gov.in/", window: "Usually closes end Nov", priority: "Portal only", notes: "" },
  { id: "tamil-nadu-post-matric-and-first-graduate", name: "Tamil Nadu Post-Matric and First Graduate", category: "State - other", group: "State", appliesTo: "Tamil Nadu", classLevel: "Class 11 onwards", levelGroup: "Class 11-12", whoFor: "Category and first-graduate students", incomeLimit: "Scheme-wise", amount: "Scheme-wise", applyAt: "tnesevai / dept portals", applyUrl: "https://escholarship.tn.gov.in/", window: "Annual cycle", priority: "Portal only", notes: "" },
  { id: "wb-swami-vivekananda-merit-cum-means", name: "WB Swami Vivekananda Merit-cum-Means", category: "State - other", group: "State", appliesTo: "West Bengal", classLevel: "Class 11 onwards", levelGroup: "Class 11-12", whoFor: "Merit and income based", incomeLimit: "Scheme-wise", amount: "Scheme-wise", applyAt: "svmcm.wbhed.gov.in", applyUrl: "https://svmcm.wbhed.gov.in/", window: "Annual cycle", priority: "Portal only", notes: "" },
  { id: "delhi-merit-and-higher-education-guarantee-schemes", name: "Delhi Merit and Higher Education Guarantee schemes", category: "State - other", group: "State", appliesTo: "Delhi", classLevel: "Class 11 onwards", levelGroup: "Class 11-12", whoFor: "Merit and income based", incomeLimit: "Scheme-wise", amount: "Scheme-wise", applyAt: "edudel.nic.in", applyUrl: "https://edudel.nic.in/", window: "Annual cycle", priority: "Portal only", notes: "" },
  { id: "odisha-pre-matric-class-9-10-and-medhabruti", name: "Odisha Pre-Matric Class 9-10 and Medhabruti", category: "State - other", group: "State", appliesTo: "Odisha", classLevel: "Class 9 onwards", levelGroup: "School (up to Class 10)", whoFor: "Category and merit students", incomeLimit: "Scheme-wise", amount: "Scheme-wise", applyAt: "scholarship.odisha.gov.in", applyUrl: "https://scholarship.odisha.gov.in/", window: "Annual cycle", priority: "Portal only", notes: "" },
  { id: "telangana-and-ap-epass-post-matric", name: "Telangana and AP ePASS Post-Matric", category: "State - other", group: "State", appliesTo: "Telangana / Andhra Pradesh", classLevel: "Class 11 onwards", levelGroup: "Class 11-12", whoFor: "Category and income based", incomeLimit: "Scheme-wise", amount: "Scheme-wise", applyAt: "telanganaepass / apepass", applyUrl: "https://telanganaepass.cgg.gov.in/", window: "Annual cycle", priority: "Portal only", notes: "" },
  { id: "sitaram-jindal-foundation-scholarship", name: "Sitaram Jindal Foundation Scholarship", category: "Corporate / CSR", group: "Other", appliesTo: "All India", classLevel: "Class 11 to PG, ITI, diploma", levelGroup: "PG / research", whoFor: "Merit-cum-means", incomeLimit: "Rs 4 lakh salaried / Rs 2.5 lakh others", amount: "Up to Rs 3,200/month, paid half-yearly by DBT", applyAt: "sitaramjindalfoundation.org", applyUrl: "https://www.sitaramjindalfoundation.org/", window: "Deadline 30 Sep 2026", priority: "High", notes: "Covers ITI and diploma - useful for Vocational track" },
  { id: "hdfc-bank-parivartan-ecss", name: "HDFC Bank Parivartan ECSS", category: "Corporate / CSR", group: "Other", appliesTo: "All India", classLevel: "Class 1-12, ITI, polytechnic, UG, PG", levelGroup: "PG / research", whoFor: "Students facing a family or personal crisis", incomeLimit: "Under Rs 2.5 lakh", amount: "Varies", applyAt: "hdfcbank.com / Buddy4Study", applyUrl: "https://www.buddy4study.com/page/hdfc-bank-parivartans-ecs-scholarship", window: "Annual cycle", priority: "High", notes: "Widest class coverage of any CSR scheme on this list" },
  { id: "tata-capital-pankh-scholarship", name: "Tata Capital Pankh Scholarship", category: "Corporate / CSR", group: "Other", appliesTo: "All India", classLevel: "Class 11-12", levelGroup: "Class 11-12", whoFor: "Economically weaker students", incomeLimit: "Scheme-wise", amount: "Up to Rs 80,000", applyAt: "tatacapital.com", applyUrl: "https://www.tatacapital.com/", window: "Annual cycle", priority: "High", notes: "" },
  { id: "tata-trusts-means-grant", name: "Tata Trusts Means Grant", category: "Corporate / CSR", group: "Other", appliesTo: "All India", classLevel: "Higher education", levelGroup: "School (up to Class 10)", whoFor: "Means-tested students", incomeLimit: "Scheme-wise", amount: "Rs 5,000 - Rs 50,000/yr against verified receipts", applyAt: "tatatrusts.org", applyUrl: "https://www.tatatrusts.org/", window: "Annual cycle", priority: "Medium", notes: "" },
  { id: "reliance-foundation-undergraduate-scholarship", name: "Reliance Foundation Undergraduate Scholarship", category: "Corporate / CSR", group: "Other", appliesTo: "All India", classLevel: "UG first year", levelGroup: "UG / diploma", whoFor: "Merit-cum-means, min 60% in Class 12", incomeLimit: "Scheme-wise", amount: "Up to Rs 2 lakh over the degree", applyAt: "scholarships.reliancefoundation.org", applyUrl: "https://www.scholarships.reliancefoundation.org/", window: "Usually opens Aug-Oct", priority: "High", notes: "5,000 awards" },
  { id: "sbi-foundation-asha-scholarship", name: "SBI Foundation Asha Scholarship", category: "Corporate / CSR", group: "Other", appliesTo: "All India", classLevel: "Class 6 to UG and PG", levelGroup: "PG / research", whoFor: "Income under approx Rs 6 lakh", incomeLimit: "Approx Rs 6 lakh", amount: "Rs 15,000 upwards by level", applyAt: "sbifoundation.in", applyUrl: "https://www.sbifoundation.in/", window: "Usually closes Nov", priority: "High", notes: "50% reservation for SC/ST" },
  { id: "infosys-foundation-scholarship", name: "Infosys Foundation Scholarship", category: "Corporate / CSR", group: "Other", appliesTo: "All India", classLevel: "UG", levelGroup: "UG / diploma", whoFor: "Income under Rs 8 lakh", incomeLimit: "Rs 8 lakh", amount: "Approx Rs 1,00,000", applyAt: "infosys.org", applyUrl: "https://www.infosys.org/infosys-foundation.html", window: "Annual cycle", priority: "Medium", notes: "" },
  { id: "kotak-shiksha-nidhi-kotak-kanya", name: "Kotak Shiksha Nidhi / Kotak Kanya", category: "Corporate / CSR", group: "Other", appliesTo: "All India", classLevel: "Class 11-12 / UG", levelGroup: "UG / diploma", whoFor: "Economically weaker students; girls", incomeLimit: "Scheme-wise", amount: "Scheme-wise", applyAt: "kotakeducation.org", applyUrl: "https://kotakeducation.org/", window: "Annual cycle", priority: "Medium", notes: "" },
  { id: "aditya-birla-scholarship", name: "Aditya Birla Scholarship", category: "Corporate / CSR", group: "Other", appliesTo: "All India", classLevel: "Professional UG / PG", levelGroup: "PG / research", whoFor: "Top-ranked students at partner institutes", incomeLimit: "", amount: "Scheme-wise", applyAt: "adityabirlascholars.net", applyUrl: "https://www.adityabirlascholars.net/", window: "Annual cycle", priority: "Low", notes: "Elite institutes only" },
  { id: "lic-golden-jubilee-foundation-scholarship", name: "LIC Golden Jubilee Foundation Scholarship", category: "Corporate / CSR", group: "Other", appliesTo: "All India", classLevel: "Class 11 onwards", levelGroup: "Class 11-12", whoFor: "Economically weaker students", incomeLimit: "Scheme-wise", amount: "Scheme-wise", applyAt: "licindia.in", applyUrl: "https://licindia.in/", window: "Annual cycle", priority: "Medium", notes: "" },
  { id: "colgate-keep-india-smiling", name: "Colgate Keep India Smiling", category: "Corporate / CSR", group: "Other", appliesTo: "All India", classLevel: "Class 11 onwards", levelGroup: "Class 11-12", whoFor: "Merit-cum-means", incomeLimit: "Scheme-wise", amount: "Scheme-wise", applyAt: "colgatecares.co.in", applyUrl: "https://www.colgatecares.co.in/", window: "Annual cycle", priority: "Medium", notes: "" },
  { id: "legrand-empowering-scholarship", name: "Legrand Empowering Scholarship", category: "Corporate / CSR", group: "Other", appliesTo: "All India", classLevel: "Class 11 onwards", levelGroup: "Class 11-12", whoFor: "Students with disabilities", incomeLimit: "Scheme-wise", amount: "Scheme-wise", applyAt: "Buddy4Study", applyUrl: "https://www.buddy4study.com/page/legrand-empowering-scholarship-program", window: "Annual cycle", priority: "Medium", notes: "" },
  { id: "buddy4study-india-foundation-scholarship", name: "Buddy4Study India Foundation Scholarship", category: "NGO / trust", group: "Other", appliesTo: "All India", classLevel: "Class 11-12, UG", levelGroup: "UG / diploma", whoFor: "Min 60% in previous class", incomeLimit: "Under Rs 8 lakh", amount: "Rs 6,000-24,000 Class 11-12; Rs 25,000-75,000 UG", applyAt: "buddy4study.com", applyUrl: "https://www.buddy4study.com/", window: "Annual cycle", priority: "High", notes: "Preference for girls, PwD, orphans and government-school students" },
  { id: "vidyadhan-sarojini-damodaran-foundation", name: "Vidyadhan (Sarojini Damodaran Foundation)", category: "NGO / trust", group: "Other", appliesTo: "All India", classLevel: "Class 10 pass onwards", levelGroup: "School (up to Class 10)", whoFor: "Meritorious low-income students", incomeLimit: "Scheme-wise", amount: "Rs 10,000 - Rs 60,000", applyAt: "vidyadhan.org", applyUrl: "https://www.vidyadhan.org/", window: "Opens after Class 10 results", priority: "High", notes: "Good fit for our Class 10 leavers" },
  { id: "faea-undergraduate-scholarship", name: "FAEA Undergraduate Scholarship", category: "NGO / trust", group: "Other", appliesTo: "All India", classLevel: "UG", levelGroup: "UG / diploma", whoFor: "Socially and economically disadvantaged", incomeLimit: "Scheme-wise", amount: "Fee plus maintenance", applyAt: "faeaindia.org", applyUrl: "https://www.faeaindia.org/", window: "Annual cycle", priority: "Medium", notes: "" },
  { id: "foundation-for-excellence-ffe", name: "Foundation for Excellence (FFE)", category: "NGO / trust", group: "Other", appliesTo: "All India", classLevel: "Professional UG", levelGroup: "UG / diploma", whoFor: "Merit-cum-means", incomeLimit: "Scheme-wise", amount: "Scheme-wise", applyAt: "ffe.org", applyUrl: "https://www.ffe.org/", window: "Annual cycle", priority: "Medium", notes: "" },
  { id: "dr-rajendra-prasad-scholarship-programme", name: "Dr. Rajendra Prasad Scholarship Programme", category: "NGO / trust", group: "Other", appliesTo: "All India", classLevel: "Class 10 pass and above", levelGroup: "School (up to Class 10)", whoFor: "Merit-cum-means", incomeLimit: "Scheme-wise", amount: "Scheme-wise", applyAt: "Buddy4Study", applyUrl: "https://www.buddy4study.com/", window: "Deadline 30 Sep 2026", priority: "Medium", notes: "" },
  { id: "vivo-kanyagyaan", name: "Vivo KanyaGyaan", category: "NGO / corporate", group: "Other", appliesTo: "All India", classLevel: "Girls entering STEM", levelGroup: "School (up to Class 10)", whoFor: "Girl students", incomeLimit: "Scheme-wise", amount: "Scheme-wise", applyAt: "Buddy4Study", applyUrl: "https://www.buddy4study.com/page/vivo-india-kanyagyaan-scholarship-program", window: "Annual cycle", priority: "Medium", notes: "" },
  { id: "nikon-scholarship-programme", name: "Nikon Scholarship Programme", category: "Corporate / CSR", group: "Other", appliesTo: "All India", classLevel: "Varies", levelGroup: "School (up to Class 10)", whoFor: "Merit-cum-means", incomeLimit: "Scheme-wise", amount: "Scheme-wise", applyAt: "Buddy4Study", applyUrl: "https://www.buddy4study.com/", window: "Deadline 23 Sep 2026", priority: "Low", notes: "" },
  { id: "vidyasaarathi-nsdl", name: "Vidyasaarathi (NSDL)", category: "Platform", group: "Other", appliesTo: "All India", classLevel: "School to PG", levelGroup: "PG / research", whoFor: "Varies by donor", incomeLimit: "Varies", amount: "Varies by donor scheme", applyAt: "vidyasaarathi.co.in", applyUrl: "https://www.vidyasaarathi.co.in/", window: "Rolling - multiple donor schemes", priority: "Medium", notes: "Aggregator platform, several corporate donors in one place" },
];
