// A curated seed list of major Gujarat colleges. Admins can extend this via Excel import.
// Used by /admin/colleges → "Seed sample data" button.

import type { TablesInsert } from "@/integrations/supabase/types";

type CollegeInsert = TablesInsert<"colleges">;

export const SEED_COLLEGES: CollegeInsert[] = [
  // Engineering / Tech
  {
    name: "Indian Institute of Technology Gandhinagar (IITGN)",
    city: "Gandhinagar",
    district: "Gandhinagar",
    type: "Government",
    affiliation: "Autonomous (IIT)",
    established: 2008,
    streams: ["engineering", "science"],
    courses: ["B.Tech CSE", "B.Tech EE", "B.Tech ME", "B.Tech Civil", "B.Tech Chemical", "B.Sc Research"],
    entrance_exams: ["JEE Advanced"],
    fees_range: "₹2.2 L / yr",
    hostel: true,
    scholarships: true,
    website: "iitgn.ac.in",
  },
  {
    name: "Dhirubhai Ambani Institute of Information & Communication Technology (DA-IICT)",
    city: "Gandhinagar",
    district: "Gandhinagar",
    type: "Private",
    affiliation: "Deemed",
    established: 2001,
    streams: ["engineering"],
    courses: ["B.Tech ICT", "B.Tech CSE", "B.Tech Maths & Computing"],
    entrance_exams: ["JEE Main"],
    fees_range: "₹2.8 L / yr",
    hostel: true,
    scholarships: true,
    website: "daiict.ac.in",
  },
  {
    name: "Sardar Vallabhbhai National Institute of Technology (SVNIT)",
    city: "Surat",
    district: "Surat",
    type: "Government",
    affiliation: "NIT (Autonomous)",
    established: 1961,
    streams: ["engineering"],
    courses: ["B.Tech CSE/EE/ME/Civil/Chem"],
    entrance_exams: ["JEE Main"],
    fees_range: "₹1.5 L / yr",
    hostel: true,
    scholarships: true,
    website: "svnit.ac.in",
  },
  {
    name: "Nirma University — Institute of Technology",
    city: "Ahmedabad",
    district: "Ahmedabad",
    type: "Private",
    affiliation: "Nirma University",
    established: 1995,
    streams: ["engineering", "management", "law"],
    courses: ["B.Tech (CSE, EC, IT, ME, Civil, Chem)", "BBA", "BA LLB"],
    entrance_exams: ["JEE Main", "CLAT"],
    fees_range: "₹1.7–2.5 L / yr",
    hostel: true,
    scholarships: true,
    website: "nirmauni.ac.in",
  },
  {
    name: "Pandit Deendayal Energy University (PDEU)",
    city: "Gandhinagar",
    district: "Gandhinagar",
    type: "Private",
    affiliation: "State Private",
    established: 2007,
    streams: ["engineering", "management", "humanities", "science"],
    courses: ["B.Tech (Petroleum, CSE, EE, ME, Civil)", "BBA", "BA Liberal Studies"],
    entrance_exams: ["JEE Main", "Direct"],
    fees_range: "₹2.5–3.5 L / yr",
    hostel: true,
    scholarships: true,
    website: "pdpu.ac.in",
  },
  {
    name: "L. D. College of Engineering",
    city: "Ahmedabad",
    district: "Ahmedabad",
    type: "Government",
    affiliation: "GTU",
    established: 1948,
    streams: ["engineering"],
    courses: ["B.E. (all branches)"],
    entrance_exams: ["GUJCET", "JEE Main"],
    fees_range: "₹50k / yr",
    hostel: true,
    scholarships: true,
    website: "ldce.ac.in",
  },
  {
    name: "Vishwakarma Government Engineering College",
    city: "Chandkheda",
    district: "Gandhinagar",
    type: "Government",
    affiliation: "GTU",
    established: 1994,
    streams: ["engineering"],
    courses: ["B.E. CSE/IT/EC/ME/Civil"],
    entrance_exams: ["GUJCET"],
    fees_range: "₹50k / yr",
    hostel: false,
    scholarships: true,
    website: "vgecg.ac.in",
  },

  // Medical
  {
    name: "B. J. Medical College",
    city: "Ahmedabad",
    district: "Ahmedabad",
    type: "Government",
    affiliation: "Gujarat University",
    established: 1946,
    streams: ["medical"],
    courses: ["MBBS", "MD/MS"],
    entrance_exams: ["NEET-UG"],
    fees_range: "₹25k / yr",
    hostel: true,
    scholarships: true,
    website: "bjmcabd.edu.in",
  },
  {
    name: "Government Medical College, Surat",
    city: "Surat",
    district: "Surat",
    type: "Government",
    affiliation: "Veer Narmad South Gujarat University",
    established: 1964,
    streams: ["medical"],
    courses: ["MBBS"],
    entrance_exams: ["NEET-UG"],
    fees_range: "₹25k / yr",
    hostel: true,
    scholarships: true,
    website: "gmcsurat.edu.in",
  },
  {
    name: "All India Institute of Medical Sciences (AIIMS), Rajkot",
    city: "Rajkot",
    district: "Rajkot",
    type: "Government",
    affiliation: "AIIMS",
    established: 2020,
    streams: ["medical"],
    courses: ["MBBS"],
    entrance_exams: ["NEET-UG"],
    fees_range: "₹6k / yr",
    hostel: true,
    scholarships: true,
    website: "aiimsrajkot.edu.in",
  },
  {
    name: "Smt. NHL Municipal Medical College",
    city: "Ahmedabad",
    district: "Ahmedabad",
    type: "Government",
    affiliation: "Gujarat University",
    established: 1963,
    streams: ["medical"],
    courses: ["MBBS"],
    entrance_exams: ["NEET-UG"],
    fees_range: "₹3.5 L / yr",
    hostel: true,
    scholarships: true,
    website: "nhlmmc.edu.in",
  },
  {
    name: "Government Dental College, Ahmedabad",
    city: "Ahmedabad",
    district: "Ahmedabad",
    type: "Government",
    affiliation: "Gujarat University",
    established: 1955,
    streams: ["medical"],
    courses: ["BDS"],
    entrance_exams: ["NEET-UG"],
    fees_range: "₹25k / yr",
    hostel: true,
    scholarships: true,
    website: "gdcahmd.edu.in",
  },

  // Pharmacy
  {
    name: "L. M. College of Pharmacy",
    city: "Ahmedabad",
    district: "Ahmedabad",
    type: "Government",
    affiliation: "Gujarat University",
    established: 1947,
    streams: ["medical", "science"],
    courses: ["B.Pharm", "M.Pharm"],
    entrance_exams: ["GUJCET", "GPAT"],
    fees_range: "₹40k / yr",
    hostel: true,
    scholarships: true,
    website: "lmcp.in",
  },
  {
    name: "Institute of Pharmacy, Nirma University",
    city: "Ahmedabad",
    district: "Ahmedabad",
    type: "Private",
    affiliation: "Nirma University",
    established: 2004,
    streams: ["medical", "science"],
    courses: ["B.Pharm", "Pharm.D"],
    entrance_exams: ["GUJCET"],
    fees_range: "₹1.5 L / yr",
    hostel: true,
    scholarships: true,
    website: "nirmauni.ac.in",
  },

  // Commerce / Business
  {
    name: "Indian Institute of Management Ahmedabad (IIMA)",
    city: "Ahmedabad",
    district: "Ahmedabad",
    type: "Government",
    affiliation: "Autonomous (IIM)",
    established: 1961,
    streams: ["management"],
    courses: ["IPM (5-yr Integrated)", "MBA (PGP)"],
    entrance_exams: ["IIM IPM", "CAT"],
    fees_range: "₹6 L / yr (IPM)",
    hostel: true,
    scholarships: true,
    website: "iima.ac.in",
  },
  {
    name: "H. L. College of Commerce",
    city: "Ahmedabad",
    district: "Ahmedabad",
    type: "Aided",
    affiliation: "Gujarat University",
    established: 1936,
    streams: ["commerce"],
    courses: ["B.Com", "M.Com"],
    entrance_exams: ["Direct admission"],
    fees_range: "₹15k / yr",
    hostel: false,
    scholarships: true,
    website: "hlcollege.edu",
  },
  {
    name: "St. Xavier's College, Ahmedabad",
    city: "Ahmedabad",
    district: "Ahmedabad",
    type: "Aided",
    affiliation: "Gujarat University",
    established: 1955,
    streams: ["science", "commerce", "humanities"],
    courses: ["B.Sc", "B.Com", "B.A.", "BBA"],
    entrance_exams: ["CUET-UG", "Direct"],
    fees_range: "₹25k / yr",
    hostel: false,
    scholarships: true,
    website: "sxca.edu.in",
  },
  {
    name: "Karnavati University",
    city: "Gandhinagar",
    district: "Gandhinagar",
    type: "Private",
    affiliation: "State Private",
    established: 2017,
    streams: ["management", "design", "law", "humanities"],
    courses: ["BBA", "B.Des", "BA LLB", "B.A. Mass Comm"],
    entrance_exams: ["Direct"],
    fees_range: "₹2.5–4 L / yr",
    hostel: true,
    scholarships: true,
    website: "karnavatiuniversity.edu.in",
  },

  // Law
  {
    name: "Gujarat National Law University (GNLU)",
    city: "Gandhinagar",
    district: "Gandhinagar",
    type: "Government",
    affiliation: "NLU (Autonomous)",
    established: 2003,
    streams: ["law"],
    courses: ["BA LLB (Hons)", "BBA LLB", "B.Com LLB", "LLM"],
    entrance_exams: ["CLAT"],
    fees_range: "₹2.5 L / yr",
    hostel: true,
    scholarships: true,
    website: "gnlu.ac.in",
  },

  // Design / Architecture
  {
    name: "National Institute of Design (NID)",
    city: "Ahmedabad",
    district: "Ahmedabad",
    type: "Government",
    affiliation: "Institute of National Importance",
    established: 1961,
    streams: ["design"],
    courses: ["B.Des (10 disciplines)", "M.Des"],
    entrance_exams: ["NID DAT"],
    fees_range: "₹3.5 L / yr",
    hostel: true,
    scholarships: true,
    website: "nid.edu",
  },
  {
    name: "CEPT University",
    city: "Ahmedabad",
    district: "Ahmedabad",
    type: "Private",
    affiliation: "Deemed",
    established: 1962,
    streams: ["design", "engineering"],
    courses: ["B.Arch", "B.Plan", "B.Construction Tech"],
    entrance_exams: ["NATA", "JEE Main Paper 2", "Direct"],
    fees_range: "₹2.4 L / yr",
    hostel: true,
    scholarships: true,
    website: "cept.ac.in",
  },
  {
    name: "NIFT Gandhinagar",
    city: "Gandhinagar",
    district: "Gandhinagar",
    type: "Government",
    affiliation: "NIFT (Statutory)",
    established: 1995,
    streams: ["design"],
    courses: ["B.Des Fashion / Textile / Accessory / Communication"],
    entrance_exams: ["NIFT"],
    fees_range: "₹3 L / yr",
    hostel: true,
    scholarships: true,
    website: "nift.ac.in/gandhinagar",
  },

  // Universities (multi-stream)
  {
    name: "Maharaja Sayajirao University of Baroda (MSU)",
    city: "Vadodara",
    district: "Vadodara",
    type: "Government",
    affiliation: "State University",
    established: 1949,
    streams: ["science", "commerce", "humanities", "engineering", "medical", "design", "law"],
    courses: ["B.E.", "B.Sc", "B.A.", "B.Com", "MBBS", "B.F.A.", "BBA", "LLB"],
    entrance_exams: ["MSU Entrance", "GUJCET", "NEET", "Direct"],
    fees_range: "₹5–60k / yr",
    hostel: true,
    scholarships: true,
    website: "msubaroda.ac.in",
  },
  {
    name: "Gujarat University",
    city: "Ahmedabad",
    district: "Ahmedabad",
    type: "Government",
    affiliation: "State University",
    established: 1949,
    streams: ["science", "commerce", "humanities"],
    courses: ["B.Sc", "B.A.", "B.Com", "M.Sc", "MBA"],
    entrance_exams: ["CUET", "Direct"],
    fees_range: "₹5–25k / yr",
    hostel: true,
    scholarships: true,
    website: "gujaratuniversity.ac.in",
  },
  {
    name: "Sardar Patel University",
    city: "Vallabh Vidyanagar",
    district: "Anand",
    type: "Government",
    affiliation: "State University",
    established: 1955,
    streams: ["science", "commerce", "humanities"],
    courses: ["B.Sc", "B.A.", "B.Com"],
    entrance_exams: ["Direct"],
    fees_range: "₹5–20k / yr",
    hostel: true,
    scholarships: true,
    website: "spuvvn.edu",
  },
  {
    name: "Saurashtra University",
    city: "Rajkot",
    district: "Rajkot",
    type: "Government",
    affiliation: "State University",
    established: 1967,
    streams: ["science", "commerce", "humanities"],
    courses: ["B.Sc", "B.A.", "B.Com"],
    entrance_exams: ["Direct"],
    fees_range: "₹5–20k / yr",
    hostel: true,
    scholarships: true,
    website: "saurashtrauniversity.edu",
  },
  {
    name: "Veer Narmad South Gujarat University",
    city: "Surat",
    district: "Surat",
    type: "Government",
    affiliation: "State University",
    established: 1965,
    streams: ["science", "commerce", "humanities"],
    courses: ["B.Sc", "B.A.", "B.Com"],
    entrance_exams: ["Direct"],
    fees_range: "₹5–20k / yr",
    hostel: true,
    scholarships: true,
    website: "vnsgu.ac.in",
  },

  // Agriculture
  {
    name: "Anand Agricultural University",
    city: "Anand",
    district: "Anand",
    type: "Government",
    affiliation: "ICAR-recognised",
    established: 2004,
    streams: ["science"],
    courses: ["B.Sc Agriculture", "B.Sc Horticulture", "B.Sc Dairy"],
    entrance_exams: ["GUJCET-Agri", "ICAR AIEEA"],
    fees_range: "₹15–25k / yr",
    hostel: true,
    scholarships: true,
    website: "aau.in",
  },
  {
    name: "Junagadh Agricultural University",
    city: "Junagadh",
    district: "Junagadh",
    type: "Government",
    affiliation: "ICAR-recognised",
    established: 2004,
    streams: ["science"],
    courses: ["B.Sc Agri", "B.Sc Fisheries"],
    entrance_exams: ["GUJCET-Agri"],
    fees_range: "₹15–25k / yr",
    hostel: true,
    scholarships: true,
    website: "jau.in",
  },

  // Polytechnic / Vocational
  {
    name: "Government Polytechnic, Ahmedabad",
    city: "Ahmedabad",
    district: "Ahmedabad",
    type: "Government",
    affiliation: "GTU",
    established: 1957,
    streams: ["vocational", "engineering"],
    courses: ["Diploma in Civil/Mech/EE/EC/CSE"],
    entrance_exams: ["ACPDC"],
    fees_range: "₹15k / yr",
    hostel: true,
    scholarships: true,
    website: "gpahmedabad.cteguj.in",
  },

  // Forensic / Special Universities
  {
    name: "National Forensic Sciences University (NFSU)",
    city: "Gandhinagar",
    district: "Gandhinagar",
    type: "Government",
    affiliation: "Institute of National Importance",
    established: 2009,
    streams: ["science", "law"],
    courses: ["B.Sc Forensic Science", "BA LLB", "B.Tech Cyber"],
    entrance_exams: ["NFSU Entrance"],
    fees_range: "₹1–1.5 L / yr",
    hostel: true,
    scholarships: true,
    website: "nfsu.ac.in",
  },
  {
    name: "Rashtriya Raksha University (RRU)",
    city: "Lavad, Gandhinagar",
    district: "Gandhinagar",
    type: "Government",
    affiliation: "Institute of National Importance",
    established: 2010,
    streams: ["humanities", "law"],
    courses: ["BA Police Science", "BA Criminology", "MBA Internal Security"],
    entrance_exams: ["RRU Entrance"],
    fees_range: "₹80k / yr",
    hostel: true,
    scholarships: true,
    website: "rru.ac.in",
  },

  // Communication / Media
  {
    name: "MICA — The School of Ideas",
    city: "Ahmedabad",
    district: "Ahmedabad",
    type: "Private",
    affiliation: "Autonomous",
    established: 1991,
    streams: ["management", "humanities"],
    courses: ["PGDM-C (PG flagship)"],
    entrance_exams: ["CAT/XAT/GMAT/MICAT"],
    fees_range: "₹12 L total (PG)",
    hostel: true,
    scholarships: true,
    website: "mica.ac.in",
  },

  // Hotel Mgmt
  {
    name: "Institute of Hotel Management (IHM), Ahmedabad",
    city: "Ahmedabad",
    district: "Ahmedabad",
    type: "Government",
    affiliation: "NCHMCT",
    established: 1984,
    streams: ["humanities", "vocational"],
    courses: ["B.Sc Hospitality & Hotel Admin"],
    entrance_exams: ["NCHM JEE"],
    fees_range: "₹85k / yr",
    hostel: true,
    scholarships: true,
    website: "ihmahmedabad.com",
  },

  // Pharmacy / Skill
  {
    name: "Kaushalya — The Skill University",
    city: "Ahmedabad",
    district: "Ahmedabad",
    type: "Government",
    affiliation: "State University",
    established: 2021,
    streams: ["vocational"],
    courses: ["Diploma & Skill certifications (NSDC)"],
    entrance_exams: ["Direct"],
    fees_range: "₹10–30k / course",
    hostel: false,
    scholarships: true,
    website: "kaushalyaskilluniversity.ac.in",
  },
];
