/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as SchoolsRouteImport } from './routes/schools'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as TeacherSessionsRouteImport } from './routes/teacher.sessions'
import { Route as TeacherSchoolsRouteImport } from './routes/teacher.schools'
import { Route as TeacherProfileRouteImport } from './routes/teacher.profile'
import { Route as TeacherSessionSessionIdRouteImport } from './routes/teacher.session.$sessionId'
import { Route as TeacherSchoolSchoolIdRouteImport } from './routes/teacher.school.$schoolId'

const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolsRoute = SchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/teacher/',
  path: '/teacher/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherSessionsRoute = TeacherSessionsRouteImport.update({
  id: '/teacher/sessions',
  path: '/teacher/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherSchoolsRoute = TeacherSchoolsRouteImport.update({
  id: '/teacher/schools',
  path: '/teacher/schools',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherProfileRoute = TeacherProfileRouteImport.update({
  id: '/teacher/profile',
  path: '/teacher/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherSessionSessionIdRoute = TeacherSessionSessionIdRouteImport.update({
  id: '/teacher/session/$sessionId',
  path: '/teacher/session/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherSchoolSchoolIdRoute = TeacherSchoolSchoolIdRouteImport.update({
  id: '/teacher/school/$schoolId',
  path: '/teacher/school/$schoolId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/programs': typeof ProgramsRoute
  '/reports': typeof ReportsRoute
  '/schools': typeof SchoolsRoute
  '/sessions': typeof SessionsRoute
  '/teachers': typeof TeachersRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/schools': typeof TeacherSchoolsRoute
  '/teacher/sessions': typeof TeacherSessionsRoute
  '/teacher/': typeof TeacherIndexRoute
  '/teacher/school/$schoolId': typeof TeacherSchoolSchoolIdRoute
  '/teacher/session/$sessionId': typeof TeacherSessionSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/programs': typeof ProgramsRoute
  '/reports': typeof ReportsRoute
  '/schools': typeof SchoolsRoute
  '/sessions': typeof SessionsRoute
  '/teachers': typeof TeachersRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/schools': typeof TeacherSchoolsRoute
  '/teacher/sessions': typeof TeacherSessionsRoute
  '/teacher': typeof TeacherIndexRoute
  '/teacher/school/$schoolId': typeof TeacherSchoolSchoolIdRoute
  '/teacher/session/$sessionId': typeof TeacherSessionSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/programs': typeof ProgramsRoute
  '/reports': typeof ReportsRoute
  '/schools': typeof SchoolsRoute
  '/sessions': typeof SessionsRoute
  '/teachers': typeof TeachersRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/schools': typeof TeacherSchoolsRoute
  '/teacher/sessions': typeof TeacherSessionsRoute
  '/teacher/': typeof TeacherIndexRoute
  '/teacher/school/$schoolId': typeof TeacherSchoolSchoolIdRoute
  '/teacher/session/$sessionId': typeof TeacherSessionSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/programs'
    | '/reports'
    | '/schools'
    | '/sessions'
    | '/teachers'
    | '/teacher/profile'
    | '/teacher/schools'
    | '/teacher/sessions'
    | '/teacher/'
    | '/teacher/school/$schoolId'
    | '/teacher/session/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/programs'
    | '/reports'
    | '/schools'
    | '/sessions'
    | '/teachers'
    | '/teacher/profile'
    | '/teacher/schools'
    | '/teacher/sessions'
    | '/teacher'
    | '/teacher/school/$schoolId'
    | '/teacher/session/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/programs'
    | '/reports'
    | '/schools'
    | '/sessions'
    | '/teachers'
    | '/teacher/profile'
    | '/teacher/schools'
    | '/teacher/sessions'
    | '/teacher/'
    | '/teacher/school/$schoolId'
    | '/teacher/session/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ProgramsRoute: typeof ProgramsRoute
  ReportsRoute: typeof ReportsRoute
  SchoolsRoute: typeof SchoolsRoute
  SessionsRoute: typeof SessionsRoute
  TeachersRoute: typeof TeachersRoute
  TeacherProfileRoute: typeof TeacherProfileRoute
  TeacherSchoolsRoute: typeof TeacherSchoolsRoute
  TeacherSessionsRoute: typeof TeacherSessionsRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
  TeacherSchoolSchoolIdRoute: typeof TeacherSchoolSchoolIdRoute
  TeacherSessionSessionIdRoute: typeof TeacherSessionSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schools': {
      id: '/schools'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof SchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/teacher'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/sessions': {
      id: '/teacher/sessions'
      path: '/teacher/sessions'
      fullPath: '/teacher/sessions'
      preLoaderRoute: typeof TeacherSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/schools': {
      id: '/teacher/schools'
      path: '/teacher/schools'
      fullPath: '/teacher/schools'
      preLoaderRoute: typeof TeacherSchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/profile': {
      id: '/teacher/profile'
      path: '/teacher/profile'
      fullPath: '/teacher/profile'
      preLoaderRoute: typeof TeacherProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/session/$sessionId': {
      id: '/teacher/session/$sessionId'
      path: '/teacher/session/$sessionId'
      fullPath: '/teacher/session/$sessionId'
      preLoaderRoute: typeof TeacherSessionSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/school/$schoolId': {
      id: '/teacher/school/$schoolId'
      path: '/teacher/school/$schoolId'
      fullPath: '/teacher/school/$schoolId'
      preLoaderRoute: typeof TeacherSchoolSchoolIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ProgramsRoute: ProgramsRoute,
  ReportsRoute: ReportsRoute,
  SchoolsRoute: SchoolsRoute,
  SessionsRoute: SessionsRoute,
  TeachersRoute: TeachersRoute,
  TeacherProfileRoute: TeacherProfileRoute,
  TeacherSchoolsRoute: TeacherSchoolsRoute,
  TeacherSessionsRoute: TeacherSessionsRoute,
  TeacherIndexRoute: TeacherIndexRoute,
  TeacherSchoolSchoolIdRoute: TeacherSchoolSchoolIdRoute,
  TeacherSessionSessionIdRoute: TeacherSessionSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
