/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as SuccessStoriesRouteImport } from './routes/success-stories'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as SchoolsRouteImport } from './routes/schools'
import { Route as ScholarshipsRouteImport } from './routes/scholarships'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as ProfileBuilderRouteImport } from './routes/profile-builder'
import { Route as ParentsRouteImport } from './routes/parents'
import { Route as HandbookRouteImport } from './routes/handbook'
import { Route as ForSchoolsRouteImport } from './routes/for-schools'
import { Route as FindCollegeRouteImport } from './routes/find-college'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CollegesRouteImport } from './routes/colleges'
import { Route as CareerRouteImport } from './routes/career'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestIndexRouteImport } from './routes/test.index'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as TestTakeRouteImport } from './routes/test.take'
import { Route as TestPayRouteImport } from './routes/test.pay'
import { Route as TeacherSessionsRouteImport } from './routes/teacher.sessions'
import { Route as TeacherSchoolsRouteImport } from './routes/teacher.schools'
import { Route as TeacherProfileRouteImport } from './routes/teacher.profile'
import { Route as RTokenRouteImport } from './routes/r.$token'
import { Route as HandbookSlugRouteImport } from './routes/handbook.$slug'
import { Route as CareerStreamRouteImport } from './routes/career.$stream'
import { Route as AdminCollegesRouteImport } from './routes/admin.colleges'
import { Route as CareerStreamIndexRouteImport } from './routes/career.$stream.index'
import { Route as TeacherSessionSessionIdRouteImport } from './routes/teacher.session.$sessionId'
import { Route as TeacherSchoolSchoolIdRouteImport } from './routes/teacher.school.$schoolId'
import { Route as CareerStreamPathRouteImport } from './routes/career.$stream.$path'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessStoriesRoute = SuccessStoriesRouteImport.update({
  id: '/success-stories',
  path: '/success-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolsRoute = SchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsRoute = ScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileBuilderRoute = ProfileBuilderRouteImport.update({
  id: '/profile-builder',
  path: '/profile-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsRoute = ParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => rootRouteImport,
} as any)
const HandbookRoute = HandbookRouteImport.update({
  id: '/handbook',
  path: '/handbook',
  getParentRoute: () => rootRouteImport,
} as any)
const ForSchoolsRoute = ForSchoolsRouteImport.update({
  id: '/for-schools',
  path: '/for-schools',
  getParentRoute: () => rootRouteImport,
} as any)
const FindCollegeRoute = FindCollegeRouteImport.update({
  id: '/find-college',
  path: '/find-college',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegesRoute = CollegesRouteImport.update({
  id: '/colleges',
  path: '/colleges',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TestRoute,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/teacher/',
  path: '/teacher/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestTakeRoute = TestTakeRouteImport.update({
  id: '/take',
  path: '/take',
  getParentRoute: () => TestRoute,
} as any)
const TestPayRoute = TestPayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => TestRoute,
} as any)
const TeacherSessionsRoute = TeacherSessionsRouteImport.update({
  id: '/teacher/sessions',
  path: '/teacher/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherSchoolsRoute = TeacherSchoolsRouteImport.update({
  id: '/teacher/schools',
  path: '/teacher/schools',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherProfileRoute = TeacherProfileRouteImport.update({
  id: '/teacher/profile',
  path: '/teacher/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const HandbookSlugRoute = HandbookSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => HandbookRoute,
} as any)
const CareerStreamRoute = CareerStreamRouteImport.update({
  id: '/$stream',
  path: '/$stream',
  getParentRoute: () => CareerRoute,
} as any)
const AdminCollegesRoute = AdminCollegesRouteImport.update({
  id: '/colleges',
  path: '/colleges',
  getParentRoute: () => AdminRoute,
} as any)
const CareerStreamIndexRoute = CareerStreamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CareerStreamRoute,
} as any)
const TeacherSessionSessionIdRoute = TeacherSessionSessionIdRouteImport.update({
  id: '/teacher/session/$sessionId',
  path: '/teacher/session/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherSchoolSchoolIdRoute = TeacherSchoolSchoolIdRouteImport.update({
  id: '/teacher/school/$schoolId',
  path: '/teacher/school/$schoolId',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerStreamPathRoute = CareerStreamPathRouteImport.update({
  id: '/$path',
  path: '/$path',
  getParentRoute: () => CareerStreamRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/career': typeof CareerRouteWithChildren
  '/colleges': typeof CollegesRoute
  '/dashboard': typeof DashboardRoute
  '/exams': typeof ExamsRoute
  '/faq': typeof FaqRoute
  '/find-college': typeof FindCollegeRoute
  '/for-schools': typeof ForSchoolsRoute
  '/handbook': typeof HandbookRouteWithChildren
  '/parents': typeof ParentsRoute
  '/profile-builder': typeof ProfileBuilderRoute
  '/programs': typeof ProgramsRoute
  '/reports': typeof ReportsRoute
  '/scholarships': typeof ScholarshipsRoute
  '/schools': typeof SchoolsRoute
  '/sessions': typeof SessionsRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/teachers': typeof TeachersRoute
  '/test': typeof TestRouteWithChildren
  '/admin/colleges': typeof AdminCollegesRoute
  '/career/$stream': typeof CareerStreamRouteWithChildren
  '/handbook/$slug': typeof HandbookSlugRoute
  '/r/$token': typeof RTokenRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/schools': typeof TeacherSchoolsRoute
  '/teacher/sessions': typeof TeacherSessionsRoute
  '/test/pay': typeof TestPayRoute
  '/test/take': typeof TestTakeRoute
  '/teacher/': typeof TeacherIndexRoute
  '/test/': typeof TestIndexRoute
  '/career/$stream/$path': typeof CareerStreamPathRoute
  '/teacher/school/$schoolId': typeof TeacherSchoolSchoolIdRoute
  '/teacher/session/$sessionId': typeof TeacherSessionSessionIdRoute
  '/career/$stream/': typeof CareerStreamIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/career': typeof CareerRouteWithChildren
  '/colleges': typeof CollegesRoute
  '/dashboard': typeof DashboardRoute
  '/exams': typeof ExamsRoute
  '/faq': typeof FaqRoute
  '/find-college': typeof FindCollegeRoute
  '/for-schools': typeof ForSchoolsRoute
  '/handbook': typeof HandbookRouteWithChildren
  '/parents': typeof ParentsRoute
  '/profile-builder': typeof ProfileBuilderRoute
  '/programs': typeof ProgramsRoute
  '/reports': typeof ReportsRoute
  '/scholarships': typeof ScholarshipsRoute
  '/schools': typeof SchoolsRoute
  '/sessions': typeof SessionsRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/teachers': typeof TeachersRoute
  '/admin/colleges': typeof AdminCollegesRoute
  '/handbook/$slug': typeof HandbookSlugRoute
  '/r/$token': typeof RTokenRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/schools': typeof TeacherSchoolsRoute
  '/teacher/sessions': typeof TeacherSessionsRoute
  '/test/pay': typeof TestPayRoute
  '/test/take': typeof TestTakeRoute
  '/teacher': typeof TeacherIndexRoute
  '/test': typeof TestIndexRoute
  '/career/$stream/$path': typeof CareerStreamPathRoute
  '/teacher/school/$schoolId': typeof TeacherSchoolSchoolIdRoute
  '/teacher/session/$sessionId': typeof TeacherSessionSessionIdRoute
  '/career/$stream': typeof CareerStreamIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/career': typeof CareerRouteWithChildren
  '/colleges': typeof CollegesRoute
  '/dashboard': typeof DashboardRoute
  '/exams': typeof ExamsRoute
  '/faq': typeof FaqRoute
  '/find-college': typeof FindCollegeRoute
  '/for-schools': typeof ForSchoolsRoute
  '/handbook': typeof HandbookRouteWithChildren
  '/parents': typeof ParentsRoute
  '/profile-builder': typeof ProfileBuilderRoute
  '/programs': typeof ProgramsRoute
  '/reports': typeof ReportsRoute
  '/scholarships': typeof ScholarshipsRoute
  '/schools': typeof SchoolsRoute
  '/sessions': typeof SessionsRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/teachers': typeof TeachersRoute
  '/test': typeof TestRouteWithChildren
  '/admin/colleges': typeof AdminCollegesRoute
  '/career/$stream': typeof CareerStreamRouteWithChildren
  '/handbook/$slug': typeof HandbookSlugRoute
  '/r/$token': typeof RTokenRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/schools': typeof TeacherSchoolsRoute
  '/teacher/sessions': typeof TeacherSessionsRoute
  '/test/pay': typeof TestPayRoute
  '/test/take': typeof TestTakeRoute
  '/teacher/': typeof TeacherIndexRoute
  '/test/': typeof TestIndexRoute
  '/career/$stream/$path': typeof CareerStreamPathRoute
  '/teacher/school/$schoolId': typeof TeacherSchoolSchoolIdRoute
  '/teacher/session/$sessionId': typeof TeacherSessionSessionIdRoute
  '/career/$stream/': typeof CareerStreamIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/career'
    | '/colleges'
    | '/dashboard'
    | '/exams'
    | '/faq'
    | '/find-college'
    | '/for-schools'
    | '/handbook'
    | '/parents'
    | '/profile-builder'
    | '/programs'
    | '/reports'
    | '/scholarships'
    | '/schools'
    | '/sessions'
    | '/success-stories'
    | '/teachers'
    | '/test'
    | '/admin/colleges'
    | '/career/$stream'
    | '/handbook/$slug'
    | '/r/$token'
    | '/teacher/profile'
    | '/teacher/schools'
    | '/teacher/sessions'
    | '/test/pay'
    | '/test/take'
    | '/teacher/'
    | '/test/'
    | '/career/$stream/$path'
    | '/teacher/school/$schoolId'
    | '/teacher/session/$sessionId'
    | '/career/$stream/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/career'
    | '/colleges'
    | '/dashboard'
    | '/exams'
    | '/faq'
    | '/find-college'
    | '/for-schools'
    | '/handbook'
    | '/parents'
    | '/profile-builder'
    | '/programs'
    | '/reports'
    | '/scholarships'
    | '/schools'
    | '/sessions'
    | '/success-stories'
    | '/teachers'
    | '/admin/colleges'
    | '/handbook/$slug'
    | '/r/$token'
    | '/teacher/profile'
    | '/teacher/schools'
    | '/teacher/sessions'
    | '/test/pay'
    | '/test/take'
    | '/teacher'
    | '/test'
    | '/career/$stream/$path'
    | '/teacher/school/$schoolId'
    | '/teacher/session/$sessionId'
    | '/career/$stream'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/career'
    | '/colleges'
    | '/dashboard'
    | '/exams'
    | '/faq'
    | '/find-college'
    | '/for-schools'
    | '/handbook'
    | '/parents'
    | '/profile-builder'
    | '/programs'
    | '/reports'
    | '/scholarships'
    | '/schools'
    | '/sessions'
    | '/success-stories'
    | '/teachers'
    | '/test'
    | '/admin/colleges'
    | '/career/$stream'
    | '/handbook/$slug'
    | '/r/$token'
    | '/teacher/profile'
    | '/teacher/schools'
    | '/teacher/sessions'
    | '/test/pay'
    | '/test/take'
    | '/teacher/'
    | '/test/'
    | '/career/$stream/$path'
    | '/teacher/school/$schoolId'
    | '/teacher/session/$sessionId'
    | '/career/$stream/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CareerRoute: typeof CareerRouteWithChildren
  CollegesRoute: typeof CollegesRoute
  DashboardRoute: typeof DashboardRoute
  ExamsRoute: typeof ExamsRoute
  FaqRoute: typeof FaqRoute
  FindCollegeRoute: typeof FindCollegeRoute
  ForSchoolsRoute: typeof ForSchoolsRoute
  HandbookRoute: typeof HandbookRouteWithChildren
  ParentsRoute: typeof ParentsRoute
  ProfileBuilderRoute: typeof ProfileBuilderRoute
  ProgramsRoute: typeof ProgramsRoute
  ReportsRoute: typeof ReportsRoute
  ScholarshipsRoute: typeof ScholarshipsRoute
  SchoolsRoute: typeof SchoolsRoute
  SessionsRoute: typeof SessionsRoute
  SuccessStoriesRoute: typeof SuccessStoriesRoute
  TeachersRoute: typeof TeachersRoute
  TestRoute: typeof TestRouteWithChildren
  RTokenRoute: typeof RTokenRoute
  TeacherProfileRoute: typeof TeacherProfileRoute
  TeacherSchoolsRoute: typeof TeacherSchoolsRoute
  TeacherSessionsRoute: typeof TeacherSessionsRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
  TeacherSchoolSchoolIdRoute: typeof TeacherSchoolSchoolIdRoute
  TeacherSessionSessionIdRoute: typeof TeacherSessionSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-stories': {
      id: '/success-stories'
      path: '/success-stories'
      fullPath: '/success-stories'
      preLoaderRoute: typeof SuccessStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schools': {
      id: '/schools'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof SchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships': {
      id: '/scholarships'
      path: '/scholarships'
      fullPath: '/scholarships'
      preLoaderRoute: typeof ScholarshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-builder': {
      id: '/profile-builder'
      path: '/profile-builder'
      fullPath: '/profile-builder'
      preLoaderRoute: typeof ProfileBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents': {
      id: '/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof ParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handbook': {
      id: '/handbook'
      path: '/handbook'
      fullPath: '/handbook'
      preLoaderRoute: typeof HandbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-schools': {
      id: '/for-schools'
      path: '/for-schools'
      fullPath: '/for-schools'
      preLoaderRoute: typeof ForSchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-college': {
      id: '/find-college'
      path: '/find-college'
      fullPath: '/find-college'
      preLoaderRoute: typeof FindCollegeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colleges': {
      id: '/colleges'
      path: '/colleges'
      fullPath: '/colleges'
      preLoaderRoute: typeof CollegesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/': {
      id: '/test/'
      path: '/'
      fullPath: '/test/'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof TestRoute
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/teacher'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/take': {
      id: '/test/take'
      path: '/take'
      fullPath: '/test/take'
      preLoaderRoute: typeof TestTakeRouteImport
      parentRoute: typeof TestRoute
    }
    '/test/pay': {
      id: '/test/pay'
      path: '/pay'
      fullPath: '/test/pay'
      preLoaderRoute: typeof TestPayRouteImport
      parentRoute: typeof TestRoute
    }
    '/teacher/sessions': {
      id: '/teacher/sessions'
      path: '/teacher/sessions'
      fullPath: '/teacher/sessions'
      preLoaderRoute: typeof TeacherSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/schools': {
      id: '/teacher/schools'
      path: '/teacher/schools'
      fullPath: '/teacher/schools'
      preLoaderRoute: typeof TeacherSchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/profile': {
      id: '/teacher/profile'
      path: '/teacher/profile'
      fullPath: '/teacher/profile'
      preLoaderRoute: typeof TeacherProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handbook/$slug': {
      id: '/handbook/$slug'
      path: '/$slug'
      fullPath: '/handbook/$slug'
      preLoaderRoute: typeof HandbookSlugRouteImport
      parentRoute: typeof HandbookRoute
    }
    '/career/$stream': {
      id: '/career/$stream'
      path: '/$stream'
      fullPath: '/career/$stream'
      preLoaderRoute: typeof CareerStreamRouteImport
      parentRoute: typeof CareerRoute
    }
    '/admin/colleges': {
      id: '/admin/colleges'
      path: '/colleges'
      fullPath: '/admin/colleges'
      preLoaderRoute: typeof AdminCollegesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/career/$stream/': {
      id: '/career/$stream/'
      path: '/'
      fullPath: '/career/$stream/'
      preLoaderRoute: typeof CareerStreamIndexRouteImport
      parentRoute: typeof CareerStreamRoute
    }
    '/teacher/session/$sessionId': {
      id: '/teacher/session/$sessionId'
      path: '/teacher/session/$sessionId'
      fullPath: '/teacher/session/$sessionId'
      preLoaderRoute: typeof TeacherSessionSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/school/$schoolId': {
      id: '/teacher/school/$schoolId'
      path: '/teacher/school/$schoolId'
      fullPath: '/teacher/school/$schoolId'
      preLoaderRoute: typeof TeacherSchoolSchoolIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career/$stream/$path': {
      id: '/career/$stream/$path'
      path: '/$path'
      fullPath: '/career/$stream/$path'
      preLoaderRoute: typeof CareerStreamPathRouteImport
      parentRoute: typeof CareerStreamRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCollegesRoute: typeof AdminCollegesRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCollegesRoute: AdminCollegesRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CareerStreamRouteChildren {
  CareerStreamPathRoute: typeof CareerStreamPathRoute
  CareerStreamIndexRoute: typeof CareerStreamIndexRoute
}

const CareerStreamRouteChildren: CareerStreamRouteChildren = {
  CareerStreamPathRoute: CareerStreamPathRoute,
  CareerStreamIndexRoute: CareerStreamIndexRoute,
}

const CareerStreamRouteWithChildren = CareerStreamRoute._addFileChildren(
  CareerStreamRouteChildren,
)

interface CareerRouteChildren {
  CareerStreamRoute: typeof CareerStreamRouteWithChildren
}

const CareerRouteChildren: CareerRouteChildren = {
  CareerStreamRoute: CareerStreamRouteWithChildren,
}

const CareerRouteWithChildren =
  CareerRoute._addFileChildren(CareerRouteChildren)

interface HandbookRouteChildren {
  HandbookSlugRoute: typeof HandbookSlugRoute
}

const HandbookRouteChildren: HandbookRouteChildren = {
  HandbookSlugRoute: HandbookSlugRoute,
}

const HandbookRouteWithChildren = HandbookRoute._addFileChildren(
  HandbookRouteChildren,
)

interface TestRouteChildren {
  TestPayRoute: typeof TestPayRoute
  TestTakeRoute: typeof TestTakeRoute
  TestIndexRoute: typeof TestIndexRoute
}

const TestRouteChildren: TestRouteChildren = {
  TestPayRoute: TestPayRoute,
  TestTakeRoute: TestTakeRoute,
  TestIndexRoute: TestIndexRoute,
}

const TestRouteWithChildren = TestRoute._addFileChildren(TestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CareerRoute: CareerRouteWithChildren,
  CollegesRoute: CollegesRoute,
  DashboardRoute: DashboardRoute,
  ExamsRoute: ExamsRoute,
  FaqRoute: FaqRoute,
  FindCollegeRoute: FindCollegeRoute,
  ForSchoolsRoute: ForSchoolsRoute,
  HandbookRoute: HandbookRouteWithChildren,
  ParentsRoute: ParentsRoute,
  ProfileBuilderRoute: ProfileBuilderRoute,
  ProgramsRoute: ProgramsRoute,
  ReportsRoute: ReportsRoute,
  ScholarshipsRoute: ScholarshipsRoute,
  SchoolsRoute: SchoolsRoute,
  SessionsRoute: SessionsRoute,
  SuccessStoriesRoute: SuccessStoriesRoute,
  TeachersRoute: TeachersRoute,
  TestRoute: TestRouteWithChildren,
  RTokenRoute: RTokenRoute,
  TeacherProfileRoute: TeacherProfileRoute,
  TeacherSchoolsRoute: TeacherSchoolsRoute,
  TeacherSessionsRoute: TeacherSessionsRoute,
  TeacherIndexRoute: TeacherIndexRoute,
  TeacherSchoolSchoolIdRoute: TeacherSchoolSchoolIdRoute,
  TeacherSessionSessionIdRoute: TeacherSessionSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
